### ISSUE TITLE
bdr appears to be trying to replicate to itself and filling up pg_xlog.

### ISSUE THREAD

**Issue by blackc2004** [2ndQuadrant/bdr#143] opened 2015-11-15 22:06 UTC
I noticed a very strange issue starting about 20 days ago and my pg_xlog has just been filling up since then.

```
HOST A: 
postgres=# select * from pg_replication_slots;
                slot_name                | plugin | slot_type | datoid | database  | active | xmin | catalog_xmin | restart_lsn
-----------------------------------------+--------+-----------+--------+-----------+--------+------+--------------+-------------
 bdr_16385_6188730679935789649_1_16385__ | bdr    | logical   |  16385 | database_name | f      |      |     28174997 | 25/7677F300
 bdr_16385_6188733518371128845_2_16385__ | bdr    | logical   |  16385 | database_name | t      |      |     38613316 | 41/7B7EDF80

select bdr.bdr_get_local_nodeid();
     bdr_get_local_nodeid
-------------------------------
 (6188730679935789649,1,16385)

SELECT     slot_name, database, active,     pg_xlog_location_diff(pg_current_xlog_insert_location(), restart_lsn) AS retained_bytes  FROM pg_replication_slots WHERE plugin = 'bdr';
                slot_name                | database  | active | retained_bytes
-----------------------------------------+-----------+--------+----------------
 bdr_16385_6188730679935789649_1_16385__ | database_name | f      |   120353015152
 bdr_16385_6188733518371128845_2_16385__ | database_name | t      |           2288
(2 rows)
```

HOST B: 

```
select * from pg_replication_slots;
                slot_name                | plugin | slot_type | datoid | database  | active | xmin | catalog_xmin | restart_lsn
-----------------------------------------+--------+-----------+--------+-----------+--------+------+--------------+-------------
 bdr_16385_6188730679935789649_1_16385__ | bdr    | logical   |  16385 | database_name | t      |      |      3499719 | 3/B53F00A8

select bdr.bdr_get_local_nodeid();
     bdr_get_local_nodeid
-------------------------------
 (6188733518371128845,2,16385)

SELECT     slot_name, database, active,     pg_xlog_location_diff(pg_current_xlog_insert_location(), restart_lsn) AS retained_bytes  FROM pg_replication_slots WHERE plugin = 'bdr';
                slot_name                | database  | active | retained_bytes
-----------------------------------------+-----------+--------+----------------
 bdr_16385_6188730679935789649_1_16385__ | database_name | t      |          68736
```

So it almost looks like HOST A is trying to replicate to itself since the replication_slots has the same node_id of itself and it's just filling up the pg_xlog.

This server has been setup since mid-may and I haven't added any new nodes. 

Can anyone help me fix this? I'm running out of HD space.

**Comment by ringerc** [comment] 2015-11-16 01:19
Drop the slot `bdr_16385_6188730679935789649_1_16385__` on the first host.

Since it will've been created ages ago and you're not likely to retain logs from then, it's hard to say how/why. Most likely a mistake during setup. BDR tries to protect against common misconfigurations like asking a node to join its self, but it's possible more checks are needed somewhere.

Also, remember to **always** include your exact version(s) in any bug report, to any software, anywhere.

**Comment by ringerc** [comment] 2015-11-16 01:20
Closing as this is more of a general support request. Please use pgsql-general for that. If you can find the original command sequence used to set up BDR and you're on at least 0.9.2, and you can reproduce the same problem with a slot created pointing to the local node, please open a bug with steps to reproduce.

**Closed by ringerc** 2015-11-16 01:20 UTC

**Comment by blackc2004** [comment] 2015-11-16 16:10
Thanks, sorry. I meant to include the versions... I posted to pgsql-general this morning. Wasn't sure where the right place to post was... How exactly do I drop the slot? 

I only see this in the documentation:
SELECT bdr.bdr_part_by_node_names(ARRAY['node-1']); which I don't think is what you mean?

```
dpkg -l | grep '^ii' | grep postgre
ii  pgdg-keyring                        2014.1                              all          keyring for apt.postgresql.org
ii  postgresql-bdr-9.4                  9.4.5-1trusty                       amd64        object-relational SQL database, version 9.4 server
ii  postgresql-bdr-9.4-bdr-plugin       0.9.3-1trusty                       amd64        BDR Plugin for PostgreSQL-BDR 9.4
ii  postgresql-bdr-client-9.4           9.4.5-1trusty                       amd64        front-end programs for PostgreSQL-BDR 9.4
ii  postgresql-bdr-contrib-9.4          9.4.5-1trusty                       amd64        additional facilities for PostgreSQL
ii  postgresql-client-common            170.pgdg14.04+1                     all          manager for multiple PostgreSQL client versions
ii  postgresql-common                   170.pgdg14.04+1                     all          PostgreSQL database-cluster manager
ii  postgresql-contrib                  9.4+170.pgdg14.04+1                 all          additional facilities for PostgreSQL (supported version)
```

**Comment by ringerc** [comment] 2015-11-17 01:17
SELECT ​pg_drop_replication_slot('slot_name')
