### ISSUE TITLE
BDR: Read replica fails to init

### ISSUE THREAD

**Issue by eloycoto** [2ndQuadrant/bdr#177] opened 2016-04-25 09:39 UTC
Hi, 

I'm adding a new read-replica but I'm having the following problem: 
```
ERROR:  XX000: tuple natts mismatch, 26 vs 27
```
I had this problem before when I added a new master node, but after use pg_basebackup + bdr_init_copy works ok, but with read-replica I'm not sure how can I proceed. 

I use pg_dump + pg_restore manually, as [bdr_initial_load script](https://github.com/2ndQuadrant/bdr/blob/bdr-plugin/next/scripts/bdr_initial_load.in) but still I'm having this problem. Any idea how can I fix this? 

Regards and thanks.

**Comment by ringerc** [comment] 2016-04-25 12:55
On 25 April 2016 at 17:39, Eloy Coto <notifications@github.com> wrote:

> Hi,
>
> I'm adding a new read-replica but I'm having the following problem:
>
> ERROR:  XX000: tuple natts mismatch, 26 vs 27
>
> I had this problem before when I added a new master node, but after use
> pg_basebackup + bdr_init_copy works ok, but with read-replica I'm not sure
> how can I proceed.
>
> I use pg_dump + pg_restore manually, as bdr_initial_load script
> <https://github.com/2ndQuadrant/bdr/blob/bdr-plugin/next/scripts/bdr_initial_load.in>
> but still I'm having this problem. Any idea how can I fix this?
>

It's fixed in git master and will be in the next release. The problem is
that if a table has dropped columns, BDR expects them to exist but be
invisible (attisdropped=t in pg_attribute). pg_dump leaves them out
entirely.

Please look for existing bugs before you report one.

See:

https://github.com/2ndQuadrant/bdr/issues/114
https://github.com/2ndQuadrant/bdr/issues/113

and the commit that fixes it:

https://github.com/2ndQuadrant/bdr/commit/9323f3e3c0a1c3f5ecfca8202503c0b421e4d919


You might be able to work around it by hacking bdr_initial_load to use the
--binary-upgrade option to pg_dump, but I think that probably has other
side-effects you won't want.

Your options are:

* Wait for the next release
* Drop and re-create the problem table so it has no dropped columns
anymore; or
* Backport that commit

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment] 2016-04-25 12:56
Duplicate of #113

**Closed by ringerc** 2016-04-25 12:56 UTC
Labels: duplicate
