### ISSUE TITLE
BDR 0.9.3 - Hang in joining BDR group

### ISSUE THREAD

**Issue by pallavisontakke** [2ndQuadrant/bdr#232] opened 2016-08-23 05:10 UTC
Install older version of BDR with commands:

sudo dnf install postgresql-bdr94-server-9.4.8_bdr2-1_2ndQuadrant.fc22
sudo dnf install postgresql-bdr94-bdr-0.9.3-1_2ndQuadrant.fc22

These packages get installed:
  postgresql-bdr94.x86_64 9.4.8_bdr2-1_2ndQuadrant.fc22                         
  postgresql-bdr94-libs.x86_64 9.4.8_bdr2-1_2ndQuadrant.fc22                    
  postgresql-bdr94-server.x86_64 9.4.8_bdr2-1_2ndQuadrant.fc22                  
  libxslt.x86_64 1.1.28-8.fc22                                                  
  postgresql-bdr94-bdr.x86_64 0.9.3-1_2ndQuadrant.fc22                          
  postgresql-bdr94-contrib.x86_64 9.4.8_bdr2-1_2ndQuadrant.fc22    

When following quickstart steps for demo database, we get a hang on second node that tries to join the BDR group.
=====================//========================
Log on 5599 BDR (second) node shows:
< 2016-08-23 04:33:11.100 UTC >FATAL:  could not send replication command "CREATE_REPLICATION_SLOT "bdr_16385_6321876816178959892_1_16385__" LOGICAL bdr": status PGRES_FATAL_ERROR: ERROR:  could not parse slot name: <98>^G
        CONTEXT:  slot "bdr_16385_6321876816178959892_1_16385__", output plugin "bdr", in the startup callback
< 2016-08-23 04:33:11.101 UTC >LOG:  worker process: bdr db: bdrdemo (PID 1634) exited with exit code 1
< 2016-08-23 04:33:16.104 UTC >LOG:  starting background worker process "bdr db: bdrdemo"
< 2016-08-23 04:33:16.111 UTC >ERROR:  previous init failed, manual cleanup is required
< 2016-08-23 04:33:16.111 UTC >DETAIL:  Found bdr.bdr_nodes entry for bdr (6321876816178959892,1,16385,) with state=i in remote bdr.bdr_nodes
< 2016-08-23 04:33:16.111 UTC >HINT:  Remove all replication identifiers and slots corresponding to this node from the init target node then drop and recreate this database and try again
====================//======================
 @ringerc comments: Really, any Pg version should work with 0.9.x.  1.0 requires 9.4.9, but older versions don't. So this shouldn't happen, and does need debugging/investigation.

**Comment by ringerc** [comment] 2016-08-23 13:49
Couldn't reproduce on Pg 9.4.6. Suspect some subtle incompatibility has arisen between 9.4.6 and 9.4.9. Since we didn't ship 0.9.x with 9.4.9 and we require it for 1.0, not too concerned. Closing.

**Closed by ringerc** 2016-08-23 13:49 UTC
Labels: bug
