### ISSUE TITLE
cannot recover from failed bdr_subscribe without deleting target database

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#77] opened 2015-05-28 23:51 UTC
commit c059823e1852ce50def4cbdbef139b0d3389d109

so, this command in SQL:

```
cio=# select bdr.bdr_subscribe('node2','host=172.17.0.10 port=5432 dbname=cio','host=172.17.0.11 port=5432 dbname=cio',replication_sets:=ARRAY['shard2']
);
```

produces this completely mangled call to bdr_initial_load:

```
[ @  @ 2015-05-28 23:42:41.282 GMT]:LOG:  Creating replica with: /usr/lib/postgresql/9.4/bin/bdr_initial_load --snapshot (null) --source "host=172.17.0.10 port=5432 dbname=cio" --target "host=172.17.0.11 port=5432 dbname=cio" --tmp-directory "/tmp/postgres-bdr-(null).1780", --pg-dump-path "/usr/lib/postgresql/9.4/bin/bdr_dump", --pg-restore-path "/usr/lib/postgresql/9.4/bin/pg_restore"
```

This is broken in two ways: 

1. use of "(null)" for the snapshot parameter.  That isn't a wierdness of logging, it's actually passing that string.

2. bad name for pg_dump executable, instead calling bdr_dump, which doesn't exist.

**Comment by anarazel** [comment] 2015-05-28 23:58
On 2015-05-28 16:51:36 -0700, Josh Berkus wrote:
> cio=# select bdr.bdr_subscribe('node2','host=172.17.0.10 port=5432 dbname=cio','host=172.17.0.11 port=5432 dbname=cio',replication_sets:=ARRAY['shard2']
> );
> 
> produces this completely mangled call to bdr_initial_load:
> 
> [ @  @ 2015-05-28 23:42:41.282 GMT]:LOG:  Creating replica with: /usr/lib/postgresql/9.4/bin/bdr_initial_load --snapshot (null) --source "host=172.17.0.10 port=5432 dbname=cio" --target "host=172.17.0.11 port=5432 dbname=cio" --tmp-directory "/tmp/postgres-bdr-(null).1780", --pg-dump-path "/usr/lib/postgresql/9.4/bin/bdr_dump", --pg-restore-path "/usr/lib/postgresql/9.4/bin/pg_restore"

I can't reproduce the '(null)' bit, you'll have to give a bit more
context.

> 2. bad name for pg_dump executable, instead calling bdr_dump, which doesn't exist.

bdr_dump is part of both bdr and udr? And is installed by make install
for me? Stock 9.4's pg_dump due to pointless arguments doesn't have the
--snapshot argument necessary for a consistent dump, 9.5's has...

**Comment by anarazel** [comment] 2015-05-29 00:09
On 2015-05-29 01:58:06 +0200, Andres Freund wrote:
> I can't reproduce the '(null)' bit, you'll have to give a bit more
> context.

Hm. I think I see how this could have happened. Any chance that there
was a failed attempt at cloning before, and you cleaned things up
manually?

**Comment by jberkus** [comment] 2015-05-29 00:17
Yep.  I haven't gotten bdr_subscribe to work even once, so I'm doing a lot of manual cleanup.  Since there is no bdr_unsubscribe() right now, manual cleanup is the only choice (and is also not documented).

Oh, I see what's happening; its another bug in the bdr_initial_load script.  It's appending a comma to bdr_dump.  Will fix manually and retest.  How do I remove that (null) thing?

**Comment by jberkus** [comment] 2015-05-29 00:25
Hmmm.  The commas are being inserted somewhere in the BDR function code.  Not sure where; I'm looking, but havent found them yet.

**Comment by anarazel** [comment] 2015-05-29 00:36
On 2015-05-28 17:17:29 -0700, Josh Berkus wrote:
> Yep.  I haven't gotten bdr_subscribe to work even once, so I'm doing a
> lot of manual cleanup.

Your manual cleanup was incomplete, that causes the problem. There
should be detection for the case; but I can't otherwise see a chance to
get into this situation.

I strongly recommend that for now you do a new CREATE DATABASE to clone
into after a failed attempt.

What exactly is the problem if you try to follow the steps outlined in
the slides from Tuesday's talk to a T?

> Oh, I see what's happening; its another bug in the bdr_initial_load
> script.  It's appending a comma to bdr_dump

Uh. It worked here just seconds ago. Where do you say it's appending a
comma?

Did you find out why you don't have a bdr_dump?

Greetings,

Andres Freund

**Comment by jberkus** [comment] 2015-05-29 00:41
I have a bdr_dump.  The issue is the comma.  Lookie here, from the logs:

[ @  @ 2015-05-28 23:42:41.282 GMT]:LOG:  Creating replica with: /usr/lib/postgresql/9.4/bin/bdr_initial_load --snapshot (null) --source "host=172.17.0.10 port=5432 dbname=cio" --target "host=172.17.0.11 port=5432 dbname=cio" --tmp-directory "/tmp/postgres-bdr-(null).1780", --pg-dump-path "/usr/lib/postgresql/9.4/bin/bdr_dump", --pg-restore-path "/usr/lib/postgresql/9.4/bin/pg_restore"

As you can see, whatever is generating that string is appending a comma after both tmp-directory and pg-dump-path which doesn't belong there, which is causing bdr_initial_load to fail.

**Comment by jberkus** [comment] 2015-05-29 00:43
Also: I don't have your slides.

**Comment by jberkus** [comment] 2015-05-29 00:43
Also, I don't have your slides.

**Comment by jberkus** [comment] 2015-05-29 00:49
Oh, ok, those commas don't matter.  

Ok, I see what's going wrong here, and it's also related to cleanup.  So the only bug here is the inability to rescue a failed subscribe without deleting the target database.  Should I file another bug on that, or is this one sufficient?

**Comment by ringerc** [comment] 2015-05-29 09:30
At this point there really aren't any plans for handling failed subscribe without dropping and re-creating the target DB.

We can probably allow it by using `--single-transaction` mode in initial copy, but that means we can't do a parallel dump and restore, which is crucial for decent sized DBs. Just like for #78 the solution here is probably to do a non-parallel `--schema-only` dump, then `COPY` table state under our own control.

This is really related to the underlying issue that we presently have to use `pg_dump` and `pg_restore` internally to copy initial state from the origin to target DB, and that limits how smart we can be about error handling and control.

**Comment by jberkus** [comment] 2015-05-29 17:32
A bdr_unsubcribe() which would remove even an unsuccessful subscribe would take care of this.

**Comment by anarazel** [comment] 2015-05-29 18:12
On 2015-05-29 02:30:03 -0700, Craig Ringer wrote:
> At this point there really aren't any plans for handling failed
> subscribe without dropping and re-creating the target DB.

Why not? It's not very hard to write the relevant code?

> This is really related to the underlying issue that we presently have
> to use `pg_dump` and `pg_restore` internally to copy initial state
> from the origin to target DB, and that limits how smart we can be
> about error handling and control.

Hm. Why is that related? Isn't it more related to having to do things in
more than one transaction? As soon as you have longer lived state than
that you can run into problems with partial clones, no? You can't abort
a failed clone if its e.g. due to a restart.

**Comment by jberkus** [comment] 2015-05-29 19:10
I just tested:
bdr_part_by_node_names() does not clean up a failed bdr_subscribe.  You still need to do all of the steps of manual cleanup.

**Comment by ringerc** [comment] 2015-06-01 13:29
It doesn't, and it's not meant to. It should really `ERROR` on an incompletely joined node.

We'll need to add a separate cleanup function, which I'm going to try to get to at some point soon…

**Comment by ringerc** [comment] 2015-06-02 07:31
Re cleanup, if we have a half `pg_restore`'d dump on the subscribing side because `pg_restore` bailed out due to a missing user account or similar, that's not something that's going to be easy to clean up w/o dropping and re-creating the db, no? Especially since the user might have other data in that DB, it might not have been empty at subscribe time.

We certainly need a convenient way to clear traces of a subscriber that failed to join, or that joined and was since lost, from the upstream side. A wrapper for `bdr_part_by_node_names` should be sufficient for that.

**Comment by jberkus** [comment] 2015-06-02 17:17
Yeah, we won't be able to recover from everything.  However, the most common reason for bdr_subscribe to fail is that the connection to one or the other database fails for some reason.  In that case, there's been zero objects created.  For that matter ... filing another feature request, moment.

**Comment by jberkus** [comment] 2015-06-02 17:33
See feature request bug #81 related to this.

**Comment by jberkus** [comment] 2015-06-02 17:36
So, what I'm proposing is: bdr_unsubscribe should do nothing about removing database objects like tables, sequences and schema.  That should be left up to the user (and put in a HINT message, probably).

**Comment by ringerc** [comment] 2015-06-19 09:32
So what you really want, by the sounds, is a way to unsubscribe/unjoin a node to turn it back into a standalone non-BDR/UDR database, including where the original join/subscribe may have failed. Correct?

**Comment by jberkus** [comment] 2015-06-19 13:47
Not quite sure what you're asking.  What I would like to happen is that, if subscribe fails, the user should be returned to a state where they can conceivably try again without deleting the target database.  In some cases, that may require the user DROPing existing database objects if there are empty tables, etc.   But they should NOT have to manually edit the BDR catalogs and/or security labels to make this happen.

**Comment by ringerc** [comment] 2015-06-19 14:23
When you say "target database" here, do you mean the *downstream* (where
subscribe was run from)?

On 19 June 2015 at 21:47, Josh Berkus <notifications@github.com> wrote:

> Not quite sure what you're asking. What I would like to happen is that, if
> subscribe fails, the user should be returned to a state where they can
> conceivably try again without deleting the target database. In some cases,
> that may require the user DROPing existing database objects if there are
> empty tables, etc. But they should NOT have to manually edit the BDR
> catalogs and/or security labels to make this happen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/2ndQuadrant/bdr/issues/77#issuecomment-113519397>.
>



-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by jberkus** [comment] 2015-06-19 14:27
Correct.  Using the terms "origin" for the database which has RW tables, and "target" for the database which is trying to get a copy of those tables.  AFAICT, no changes are made on the origin node which require undoing other than the replication slot.

**Comment by ringerc** [comment] 2015-06-19 14:30
OK.

The only realistic way I see to do this in the short-medium term is to
offer the option of doing the initial load step as a pg_dump | pg_restore
--single-transaction .

**Comment by jberkus** [comment] 2015-06-19 14:31
Craig: I don't understand why that's related.

**Comment by ringerc** [comment] 2015-06-19 14:34
At least one failure case is with an incomplete or failed pg_restore . We
can't handle a partial restore of the upstream DB.

Other failure cases that we can't detect in advance, like slot creation,
should be handleable with a cleanup function for failed subscribes, and/or
by just allowing unsubscribe to clean up after such failures. It just won't
work if there was a partial restore of the upstream.

**Comment by jberkus** [comment] 2015-06-19 14:37
See what I said about possibly leaving it up to the user to DROP objects in the target database.  The important thing is to not have to hack the BDR catalogs and security labels.

**Comment by ringerc** [comment] 2015-06-19 14:45
Yes, that I agree with, and tend to think it should be handled with a
cleanup helper or by letting unsubscribe deal with failed subscribes.

It's likely that some redesign is going to be needed in terms of how UDR
subscriptions are represented in BDR's catalogs, and it's certainly
something to address then or preferably before.

**Comment by PJMODOS** [comment] 2016-05-04 19:12
closing as UDR is deprecated in favour of pglogical

**Closed by PJMODOS** 2016-05-04 19:12 UTC
Labels: enhancement
