### ISSUE TITLE
Bug in BDR 1.0 DDL replication

### ISSUE THREAD

**Issue by bneumeier** [2ndQuadrant/bdr#237] opened 2016-09-07 19:10 UTC
I've found a bug in DDL replication for BDR 1.0.0 that is triggered when renaming primary key constraints, The same bug may occur with other constraint types; I've only checked this one test case, though.

Reproducing the issue:

1. Create an empty database "testdb" and set up at least a two-node BDR group.
2. Create a table: CREATE TABLE ddlrepl (id integer, name character varying(255), constraint ddlrepl_pk primary key (id));
3. Rename the constraint: ALTER TABLE ddlrepl RENAME CONSTRAINT ddlrepl_pk TO ddlrepl_pkey;
4. Observe that on the other member of the BDR group, there is a repeated attempt to apply this as the invalid command "ALTER CONSTRAINT public.ddlrepl RENAME CONSTRAINT ddlrepl_pk TO ddlrepl_pkey" instead of ALTER TABLE, resulting in broken replication.

I was able to repair replication in the test case database using bdr.skip_changes_upto. I had to add 1 to the commit LSN that was reported as failing in the postgresql log, which doesn't seem to match the BDR documentation for that function; is that the right way to do it?

**Comment by ringerc** [comment] 2016-09-09 05:14
On 8 September 2016 at 03:10, Brett Neumeier <notifications@github.com>
wrote:

> I've found a bug in DDL replication for BDR 1.0.0 that is triggered when
> renaming primary key constraints, The same bug may occur with other
> constraint types; I've only checked this one test case, though.
>

Thanks for the report. I can reproduce the issue here.

The following diff shows the behaviour in the regression tests:


diff --git a/sql/ddl/alter_table.sql b/sql/ddl/alter_table.sql
index b401b5e..c99ac94 100644
--- a/sql/ddl/alter_table.sql
+++ b/sql/ddl/alter_table.sql
@@ -125,6 +125,13 @@ SELECT
pg_xlog_wait_remote_apply(pg_current_xlog_location(), pid) FROM pg_stat_r
 \c regression
 \d+ test_tbl

+\c postgres
+\d+ test_tbl
+ALTER TABLE test_tbl RENAME CONSTRAINT test_tbl_pkey TO test_ddl_pk;
+SELECT pg_xlog_wait_remote_apply(pg_current_xlog_location(), pid) FROM
pg_stat_replication;
+\c regression
+\d+ test_tbl
+
 DROP TABLE test_tbl;

 SELECT pg_xlog_wait_remote_apply(pg_current_xlog_location(), pid) FROM
pg_stat_replication;


it's clearly a DDL deparse bug, since the logs produce:

[2016-09-09 05:12:21.586 GMT] [30753] [] ERROR:  syntax error at or near
"CONSTRAINT" at character 7
[2016-09-09 05:12:21.586 GMT] [30753] [] CONTEXT:  during DDL replay of ddl
statement: ALTER CONSTRAINT public.test_tbl RENAME CONSTRAINT test_tbl_pkey
TO test_ddl_pk



-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment] 2016-09-09 05:30
The problem is in src/backend/tcop/deparse_utility.c in
deparse_RenameStmt's case OBJECT_CONSTRAINT, where we write:

                                fmtstr = psprintf("ALTER %s
%%{identity}D RENAME CONSTRAINT %%{conname}I TO %%{newname}I",

stringify_objtype(node->renameType));

but here node->renameType is OBJECT_CONSTRAINT, even though the
command is actually part of ALTER TABLE. (Or in other situations,
ALTER DOMAIN).

Fixed by commit a831a73 to bdr-pg tree, with new tests in
bdr-plugin/next 765c5ad .

Thanks for a good report that made this a quick fix.

**Closed** 2016-09-09 05:30 UTC
Labels: bug, ddl-replication
