### ISSUE TITLE
ERROR replication slot doesn't exist. But it should not be.

### ISSUE THREAD

**Issue by turtle-bazon** [2ndQuadrant/bdr#259] opened 2016-10-21 12:06 UTC
In logs I see
`ERROR:  replication slot "bdr_28729_6328237501389361655_1_19057__" does not exist`
Before I removed all nodes and remove bdr from local node. No record b pg_replication_slots. So, it is actually doesn't exist. But why it write it to log? What it whant to do?

**Comment by ringerc** [comment] 2016-10-21 12:24
Please file complete bug reports, including at minimum:

* Exact BDR and PostgreSQL version
* More complete log excerpts
* If possible, the steps taken to reach the problem from a clean install, i.e. steps to reproduce, with exact commands etc. At bare minimum a description of the deployment, what changed or what actions were taken recently before the error/problem, etc.

Right now I can't help you since I have absolutely no idea what it's connecting to, why the expected slot isn't there, why it expects that slot to be there, etc.

I'm closing this issue; feel free to reopen or leave a comment if you can supply the suggested level of detail. In this case, I'd need to see at least the contents of these queries run on each node *as well* as the above minimum standard for any bug report:

```
select * from pg_replication_slots;
select * from bdr.bdr_nodes;
select * from bdr.bdr_connections;
```

... and if possible, the logs on each node at the time the error *first* started appearing.

It's OK to edit the output to mask passwords and IP addresses, replace revealing hostnames with generic placeholders etc, but ONLY if you say you've done so and do it consistently.

**Closed** 2016-10-21 12:24 UTC

**Comment by turtle-bazon** [comment] 2016-10-21 12:31
```zs=# select * from pg_replication_slots ;
 slot_name | plugin | slot_type | datoid | database | active | xmin | catalog_xmin | restart_lsn 
-----------+--------+-----------+--------+----------+--------+------+--------------+-------------
(0 строк)

zs=# select * from bdr.bdr_nodes;
ERROR:  relation "bdr.bdr_nodes" does not exist
СТРОКА 1: select * from bdr.bdr_nodes;

zs=# select * from bdr.bdr_connections;
ERROR:  relation "bdr.bdr_connections" does not exist
СТРОКА 1: select * from bdr.bdr_connections;

zs=# \connect postgres
Вы подключены к базе данных "postgres" как пользователь "postgres".

postgres=# \l
                                      Список баз данных
       Имя        | Владелец | Кодировка | LC_COLLATE  |  LC_CTYPE   |     Права доступа     
------------------+----------+-----------+-------------+-------------+-----------------------
 bdr_supervisordb | postgres | UTF8      | ru_RU.UTF-8 | ru_RU.UTF-8 | 
 postgres         | postgres | UTF8      | ru_RU.UTF-8 | ru_RU.UTF-8 | 
 template0        | postgres | UTF8      | ru_RU.UTF-8 | ru_RU.UTF-8 | =c/postgres          +
                  |          |           |             |             | postgres=CTc/postgres
 template1        | postgres | UTF8      | ru_RU.UTF-8 | ru_RU.UTF-8 | =c/postgres          +
                  |          |           |             |             | postgres=CTc/postgres
 zs              | zeustrak | UTF8      | ru_RU.UTF-8 | ru_RU.UTF-8 | 
(5 строк)

```

**Comment by turtle-bazon** [comment] 2016-10-21 12:39
```
# apt-cache show postgresql-bdr-9.4|grep Version
Version: 9.4.9-1wheezy

# apt-cache show postgresql-bdr-9.4-bdr-plugin|grep Version
Version: 1.0.1-1wheezy

```

**Comment by ringerc** [comment] 2016-10-21 13:13
OK, and the rest? How'd you get to this point? Please re-read my comment.

**Comment by turtle-bazon** [comment] 2016-10-21 14:05
Three nodes was in btr and worked nice. After while I removed nodes by
`select bdr.remove_node_by_node_names(ARRAY['node2', 'node3']);`
After that I've executed on node2 and node3:
`select bdr.remove_bdr_from_local_node();`
And on node1:
`select bdr.remove_bdr_from_local_node(true)`
And on all nodes done:
`drop extension bdr;`
`drop extension btree_gist;`

What I copied for first node - same for others.

**Comment by turtle-bazon** [comment] 2016-10-21 14:09
Oh, sorry. I've forgot about node4. All ok now. Plelase, close ticket.

**Comment by ringerc** [comment] 2016-10-25 18:23
Please file complete bug reports, including at minimum:

* Exact BDR and PostgreSQL version
* More complete log excerpts
* If possible, the steps taken to reach the problem from a clean install,
i.e. steps to reproduce, with exact commands etc. At bare minimum a
description of the deployment, what changed or what actions were taken
recently before the error/problem, etc.

Right now I can't help you since I have absolutely no idea what it's
connecting to, why the expected slot isn't there, why it expects that slot
to be there, etc.

I'm closing this issue; feel free to reopen or leave a comment if you can
supply the suggested level of detail. In this case, I'd need to see at
least the contents of these queries run on each node *as well* as the above
minimum standard for any bug report:

select * from pg_replication_slots;
select * from bdr.bdr_nodes;
select * from bdr.bdr_connections;

... and if possible, the logs on each node at the time the error *first*
started appearing.
