### ISSUE TITLE
Removing bdr from node and then adding a new table corrupts the order of schema objects in pg_dump

### ISSUE THREAD

**Issue by lucecca** [2ndQuadrant/bdr#309] opened 2018-07-24 10:34 UTC
Hi to all,
here below the details of my environment:

- bdr-postgres version: **9.4.18**
- bdr-plugin version: **1.0.7**

Both are compiled from source code downloaded directly from github
bdr-postgres compiled with the following configure directives: **./configure --prefix=/usr/local/bdr-pg --enable-debug --with-openssl**; while bdr-plugin compiled with the following configure directives:
**./configure --prefix=/usr/local/bdr-pg**

We have a cluster of 4 nodes and time by time we have to alter the structure of the schema doing, therefore, some ddl replication.

I've read the [limitation](http://bdr-project.org/docs/0.9.0/ddl-replication-statements.html) and the forbidden ddl statement with bdr, so I'm aware that tables with OIDs are not supported and neither they will be supported.
Unfortunately our apllication strongly relies on tables' oids, therefore all of our tables are created with OIDS set to true. 

When we have to add new tables I was following this procedure:

1. part a node from the cluster via: select bdr.bdr_part_by_node_names(ARRAY['node1']);
2. remove bdr from the parted node (node1) via: select bdr.remove_bdr_from_local_node();
3. drop the bdr extensions from node1;
4. create the new table with oids on node 1;
5. create a new bdr_group;
6. use bdr_init_copy for the node2,node3,node4 to get the new schema and join the new bdr cluster;

Unfortunately the issue that I'm facing is that any logical backup carried by pg_dump or bdr_dump after the new table was created does not mantain the proper order between views and tables.
It happens, not for all the views, that some views are saved in the dump file before the referenced tables therefore unless to manually edit the logical dump the restore will partially fails.
Is this one an issue faced by someone else?
Regards,
luca

**Comment by emanuelsteen** [comment] 2019-02-18 23:07
We are seeing similar issues.

**Comment by ringerc** [comment] 2019-02-19 03:25
The problem is with step 2. There was a bug fixed in `bdr.remove_bdr_from_local_node` in BDR 2.0.7 that I though I'd backported to 1.0 but I can't see any sign of it. I'll see if I can backport it now.

**Comment by ringerc** [comment] 2019-02-19 03:26
**do not use `bdr.remove_bdr_from_local_node` until this is fixed** as it will corrupt system catalogs due to a bug in this statement:

```
    DELETE FROM pg_depend
    WHERE classid = 'pg_trigger'::regclass
      AND objid = _truncate_tg.tgobjid
      AND (refclassid = 'pg_proc'::regclass AND refobjid = 'bdr.queue_truncate'::regproc)
          OR
          (refclassid = 'pg_class'::regclass AND refobjid = _truncate_tg.tgrelid);
```

**Comment by ringerc** [comment] 2019-02-19 05:22
Fixed by commit b5675c2a1d1d0a8dd4261c945b2420112a6db29b - will be included when we release BDR 2.0.8, but you can safely update to this 2.0.7.1 interim release now.

**Closed by ringerc** 2019-02-19 05:22 UTC

**Comment by emanuelsteen** [comment] 2019-02-21 15:50
Just want to confirm it fixes the issue

**Comment by martinmarques** [comment] 2019-03-04 21:29
I believe @ringerc actually meant 1.0.8 ;)

**Comment by csdillard** [comment] 2019-04-15 19:21
I am encountering this bug in my system where `remove_bdr_from_local_node` has been called.  Is there a way to manually cause PostgreSQL to rebuild the `pg_depend` rows for particular objects in my database (without manually creating those rows myself)?
