### ISSUE TITLE
BDR: Removing and re-adding a node. 

### ISSUE THREAD

**Issue by stuszynski** [2ndQuadrant/bdr#122] opened 2015-09-17 19:25 UTC
Hi! We have a cluster with multiple databases that is using BDR to replicate to other clusters. Is there a way to fully remove a node from BDR group so I could re-add it  later (as a fresh node) and reinitiate replication without reinit (change node_sysid?) a whole cluster?

**Comment by ringerc** [comment] 2015-09-18 05:46
On 18 September 2015 at 03:25, Stanisław Tuszyński <notifications@github.com
> wrote:

> Hi! We have a cluster with multiple databases that is using BDR to
> replicate to other clusters. Is there a way to fully remove a node from BDR
> group so I'll would to re-add it later (as a fresh node) and reinitiate
> replication without reinit (change node_sysid?) a whole cluster?
>

Once a node is removed you *must* drop the database and re-create the
database. You cannot rejoin a node once removed.

There's no need to change the sysid. A new database is sufficient, as each
database is considered an independent node.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment] 2015-09-18 05:47
On 18 September 2015 at 03:25, Stanisław Tuszyński <notifications@github.com
> wrote:

> Hi! We have a cluster with multiple databases that is using BDR to
> replicate to other clusters. Is there a way to fully remove a node from BDR
> group so I'll would to re-add it later (as a fresh node) and reinitiate
> replication without reinit (change node_sysid?) a whole cluster?
>
>
> Just noticed the second part.

You can't resume replication once the node is removed. That's why we have
node removal. Otherwise you'd just turn it off, and turn it back on at some
later stage. The whole point of node removal is to free resources on the
remaining servers that must be retained in order to allow a node to rejoin.

If you want to shut a node down for a while you can just shut it down. Keep
in mind that this will prevent DDL from being done while it's offline,
though.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment] 2015-09-18 06:03
Closing: not a bug

**Closed by ringerc** 2015-09-18 06:03 UTC

**Comment by ringerc** [comment] 2019-02-05 06:17
Some further explanation I wrote elsewhere that I'll repeat here:

If you part a node, it's parted, it cannot rejoin. If you want a node to be able to rejoin, don't part it; a node can operate isolated from its peers for an extended period without being parted. You only have to part a node if you want to do DDL since you can't get the global DDL lock with any node offline. Or if you're running out of WAL space on the remaining nodes due to the replication slots for the offline node not advancing.

If you part a node, the remaining nodes throw away the book keeping information they use to keep track of replay positions and allow the nodes to sync up again when the offline node comes back online. It is not possible to "re-join" the node, though it can be stripped of BDR metadata using `bdr.remove_bdr_from_local_node` and used to seed a new independent BDR cluster.
