### ISSUE TITLE
Does BDR "keep" WAL segments (forever) if a remote node is down?

### ISSUE THREAD

**Issue by mz407f** [2ndQuadrant/bdr#166] opened 2016-03-10 23:52 UTC
Suppose I have 4 separate geographical sites, VPNed, and all BDR'ed together, and working fine.  Suddenly, connectivity to a remote site goes down (not that this has ever happened to me) for 48 hours.

Will all the participating BDR nodes "know" that site X is down, and "keep" their WAL files until connectivity is restored?  --or-- Do I have to futz around with:

wal_keep_segments=XX

Until I have 2-3 days worth of WAL files around?

Thanks

**Comment by ringerc** [comment] 2016-03-11 00:12
That's what replication slots are for - to retain the required amount of
WAL.

See the PostgreSQL and BDR manuals for details on WAL retention and
monitoring related to it. Note in particular that you have to be careful
not to let pg_xlog fill up.

(Closing, not a bug)

**Closed by ringerc** 2016-03-11 00:12 UTC
