### ISSUE TITLE
Replication breaks when adding an index using the "ll_to_earth()" function from the "earthdistance" extension

### ISSUE THREAD

**Issue by jddonat** [2ndQuadrant/bdr#252] opened 2016-10-12 23:06 UTC
Steps to create:

```
create extension if not exists cube;
create extension if not exists earthdistance;

create table zip_code_geo_poly_data (
	id serial not null primary key,
	zip_code	text,
	latitude	numeric,
	longitude	numeric	
);

CREATE INDEX zip_code_geo_poly_data_ll_to_earth 
ON zip_code_geo_poly_data 
USING gist(ll_to_earth(latitude, longitude));
```

error seen in the logs of replication peers:
```
2016-10-12 15:14:21.240 PDT [10218]: [57fbc7a2.27ea-99] [] user=,db= LOG:  starting background worker process "bdr (6339880391710775243,2,16416,)->bdr (6339879871191496265,1,"
2016-10-12 15:14:21.301 PDT [29316]: [57feb5bd.7284-1] [] user=,db= ERROR:  function earth() does not exist at character 23
2016-10-12 15:14:21.301 PDT [29316]: [57feb5bd.7284-2] [] user=,db= HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2016-10-12 15:14:21.301 PDT [29316]: [57feb5bd.7284-3] [] user=,db= QUERY:  SELECT cube(cube(cube(earth()*cos(radians($1))*cos(radians($2))),earth()*cos(radians($1))*sin(radians($2))),earth()*sin(radians($1)))::earth
2016-10-12 15:14:21.301 PDT [29316]: [57feb5bd.7284-4] [] user=,db= CONTEXT:  SQL function "ll_to_earth" during inlining
        during DDL replay of ddl statement: CREATE  INDEX  zip_code_geo_poly_data_ll_to_earth ON public.zip_code_geo_poly_data USING gist (public.ll_to_earth((latitude)::double precision, (longitude)::double precision) public.gist_cube_ops)   
        apply QUEUED_DDL in commit 6AA/90BEF9D8, xid 4281282650 commited at 2016-10-12 15:11:53.18286-07 (action #2) from node (6339879871191496265,1,16416)
2016-10-12 15:14:21.313 PDT [10218]: [57fbc7a2.27ea-100] [] user=,db= LOG:  worker process: bdr (6339880391710775243,2,16416,)->bdr (6339879871191496265,1, (PID 29316) exited with exit code 1
```
the specific error is:  **ERROR:  function earth() does not exist at character 23**

**Comment by jddonat** [comment] 2016-10-13 19:38
So I have created a workaround.  It works for my needs but not sure it is necessarily a viable generalized solution for everyone nor for all future scenarios I may run into.

I just prefixed all functions referenced within "ll_to_earth" with "public.", resulting in:

```
CREATE OR REPLACE FUNCTION ll_to_earth(
    double precision,
    double precision)
  RETURNS earth AS
'SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians($1))*cos(radians($2))),public.earth()*cos(radians($1))*sin(radians($2))),public.earth()*sin(radians($1)))::public.earth'
  LANGUAGE sql IMMUTABLE STRICT
  COST 100;
```

This can also be applied directly to downstream peers that are stuck by wrapping the statement with:
```
set bdr.skip_ddl_locking = true;
set bdr.skip_ddl_replication = true;

CREATE OR REPLACE FUNCTION ll_to_earth ...

set bdr.skip_ddl_locking = false;
set bdr.skip_ddl_replication = false;
```




Now, the question I have is, given the following entry in pg_hba.conf:
`host    replication     bdr             192.168.1.x/32           trust`

and a login role:
```
CREATE ROLE bdr LOGIN
  PASSWORD 'bdr'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
```
and bdr_group_create and bdr_group_join using dsn's like 
```
SELECT bdr.bdr_group_create(
      local_node_name := 'node1',
      node_external_dsn := 'user=bdr password=bdr host=xxxxxx port=5432 dbname=db'
);
```

what is the "search_path" the statements should be using?

I see the ERROR in the log has no user or db assigned "user=,db="
`2016-10-12 15:14:21.301 PDT [29316]: [57feb5bd.7284-1] [] user=,db= ERROR:  function earth() does not exist at character 23`

**Comment by jddonat** [comment] 2016-10-13 22:32
The question I have is, given the following entry in pg_hba.conf:
`host    replication     bdr             192.168.1.x/32           trust`

and a login role:
```
CREATE ROLE bdr LOGIN
  PASSWORD 'bdr'
  SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
```
and bdr_group_create and bdr_group_join using dsn's like 
```
SELECT bdr.bdr_group_create(
      local_node_name := 'node1',
      node_external_dsn := 'user=bdr password=bdr host=xxxxxx port=5432 dbname=db'
);
```

what is the "search_path" the statements should be using when being replayed?  Why can't we see "earth()", when logged in as "bdr" using psql or pgadmin, "select * from earth();" returns a value.

I see the ERROR in the log has no user or db assigned "user=,db="
`2016-10-12 15:14:21.301 PDT [29316]: [57feb5bd.7284-1] [] user=,db= ERROR:  function earth() does not exist at character 23`

Is the reply process using special access provided by the "REPLICATION" privilege that bypasses the normal query engine?

**Comment by ringerc** [comment] 2016-10-14 04:17
Interesting issue. What BDR version are you using exactly? Please always
show output of bdr.bdr_version() in all bugs, mailing list posts, etc.



Can you please show the output of:


SELECT * FROM bdr.bdr_queued_commands ORDER BY queued_at DESC ;


from the oldest mention of earth() or ll_to_earth() onward ?


search_path shouldn't be relevant in bdr 1.0, since DDL deparse normalizes
it. Maybe we have a deparse bug where it fails to qualify something with
the search_path. I'll need to see the above output to be sure.

Re the logs having no user or DB assigne,d that's not strictly the case.
It's a limitation in how PostgreSQL's log_line_prefix processing handles
background workers. There is a user, it's just not visible there.
​

**Comment by jddonat** [comment] 2016-10-14 05:43
bdr_version: "1.0.0--"

output from queued_commands
```
"6AE/1C3EB448";"2016-10-13 22:27:04.997856-07";"postgres";"CREATE SEQUENCE";"CREATE  SEQUENCE public.zip_code_geo_poly_data_id_seq CACHE 1 NO CYCLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 RESTART 1 USING local"
"6AE/1C3EB448";"2016-10-13 22:27:04.997856-07";"postgres";"ALTER SEQUENCE";"ALTER SEQUENCE public.zip_code_geo_poly_data_id_seq OWNED BY public.zip_code_geo_poly_data.id "
"6AE/1C3EB448";"2016-10-13 22:27:04.997856-07";"postgres";"CREATE TABLE";"CREATE  TABLE  public.zip_code_geo_poly_data (id pg_catalog.int4 DEFAULT pg_catalog.nextval('public.zip_code_geo_poly_data_id_seq'::pg_catalog.regclass) NOT NULL , zip_code pg_catalog.text   COLLATE pg_catalog."default", latitude pg_catalog."numeric"   , l (...)"
"6AE/1C3EB448";"2016-10-13 22:27:04.997856-07";"postgres";"CREATE INDEX";"CREATE  INDEX  zip_code_geo_poly_data_ll_to_earth ON public.zip_code_geo_poly_data USING gist (public.ll_to_earth((latitude)::double precision, (longitude)::double precision) public.gist_cube_ops)   "
"6AE/1C3EB448";"2016-10-13 22:27:04.997856-07";"postgres";"CREATE EXTENSION";"CREATE EXTENSION IF NOT EXISTS cube SCHEMA public"
"6AE/1C3EB448";"2016-10-13 22:27:04.997856-07";"postgres";"CREATE EXTENSION";"CREATE EXTENSION IF NOT EXISTS earthdistance SCHEMA public"

```

**Comment by ringerc** [comment] 2016-10-14 06:18
Aha, I see.

While we explicitly schema-qualify everything in the command:

CREATE  INDEX  zip_code_geo_poly_data_ll_to_earth ON
public.zip_code_geo_poly_data USING gist
(public.ll_to_earth((latitude)::double precision, (longitude)::double
precision) public.gist_cube_ops)


we don't capture and set the search_path, since we figure everything's
fully qualified. But in fact there is an SQL function that's inlined on the
downstream, so we re-interpret its contents according to the current
search_path. Since BDR clears the search_path in apply to protect against
mistaken object name clashes and detect unqualified names, this throws an
error.

​I won't be able to fix this in BDR 1.0. It'll require us to capture the
search_path on the DDL execution side and replicate with it set. That's not
perfect either, since differences in what exists on the search_path on each
end can cause incorrect replay, but it's the only real solution for this
other than requiring that all inlineable functions also be fully qualified
in all 3rd pty code.

To work around this for now, redefine the function ll_to_earth(...) to
explicitly schema-qualify the earth() function as public.earth() .

**Comment by ringerc** [comment] 2016-10-14 06:19
By the way, this is actually technically a minor bug in the
earthdistance extension. ll_to_earth(...) assumes it'll always be
executed with 'public' in the search_path before any other definition
of earth(). Please submit a PostgreSQL bug.

**Comment by jddonat** [comment] 2016-10-15 00:16
Thanks...PostgresSQL bug #14372

**Comment by ringerc** [comment] 2016-10-18 04:38
Thanks. I don't think we can ever truly comprehensively prevent this, the root cause was a (minor) issue in PostgreSQL contrib, and the improvements in the coming 9.6-compatible BDR will help address it, so I'm closing this issue.

**Closed by ringerc** 2016-10-18 04:38 UTC

**Comment by joekohlsdorf** [comment] 2018-04-06 14:13
A word of advice to anyone finding this workaround: You'll fix one problem with it but be aware that it breaks `pg_upgrade`.
