### ISSUE TITLE
Database get locked after doing ALTER TABLE ... OWNER TO ... immediately after CREATE SEQUENCE

### ISSUE THREAD

**Issue by winggundamth** [2ndQuadrant/bdr#4] opened 2015-03-05 17:03 UTC
After I setup BDR with 2 nodes and doing SET default_sequenceam=bdr. When I do below commands in sequence immediately, the database will get locked on ALTER TABLE command

```sql
CREATE SEQUENCE auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1; 
ALTER TABLE public.auth_group_id_seq OWNER TO user;
```

I found that after doing CREATE SEQUENCE you have to wait at least 1 second before you can do ALTER TABLE command and it won't get locked.

**Comment by anarazel** [comment] 2015-03-05 17:20
Hah, that's a good one. I can see the problem, will investigate. If you need to work around it you can SELECT pg_cancel_backend() the 'perdb' worker, that'll resolve the problem.

**Comment by ringerc** [comment] 2015-04-01 07:44
@anarazel Did anything happen with this one? Just checking before I pick it up to look into it.

**Comment by anarazel** [comment] 2015-04-01 10:37
On 2015-04-01 00:44:04 -0700, Craig Ringer wrote:
> @anarazel Did anything happen with this one? Just checking before I pick it up to look into it.

Let me check, I seem to recall having some pending changes.

**Comment by anarazel** [comment] 2015-05-25 00:16
I've seen something similar in the past. But I now tried to reproduce this with various scenarios, and I can't anymore. I see a potentially problematic scenario, which I'm going to fix. But given I can't reproduce the problem anymore, I can't guarantee it's this problem.

**Comment by anarazel** [comment] 2015-05-25 00:17
Any chance you could check whether the issue still occurs with /next? And if so, try to describe your setup in a bit more detail?

**Comment by ringerc** [comment] 2015-05-26 08:33
Similar to #52 too.

**Comment by PJMODOS** [comment] 2015-06-29 19:19
#52 is deparse issue, doesn't seem it has anything to do with this

Can't reproduce this one on current version so closing, if the issue persist please reopen.

**Closed by PJMODOS** 2015-06-29 19:19 UTC
Labels: bug, ddl-replication

**Comment by kforte90** [comment] 2015-06-29 22:27
Exact issue doesn't happen anymore.  One issue with global objects such as 'users' is that if a DBA forgets to create them globally with 'bdr.bdr_replicate_ddl_command' (SELECT bdr.bdr_replicate_ddl_command('CREATE USER anotheruser;'), the user names won't be replicated.  We may want to issue a error message in BDR is someone tries to create a user without the function 'bdr.bdr_replicate_ddl_command'.  Global objects are tricky in a distributed database.
