### ISSUE TITLE
BDR failing with "tuple natts mismatch"

### ISSUE THREAD

**Issue by dwierenga** [2ndQuadrant/bdr#182] opened 2016-05-04 20:20 UTC
I have a 4 machine cluster, with 2 BDR databases on each instance.  

The cluster was initialized on a single database on a single node, then cloned to the other 3 nodes with `bdr_init_copy`.  That set up has worked for weeks.  
I monitor the replication with [this SQL](https://gist.github.com/dwierenga/6a5382002dcbbee07b7529ba0e3ab735), and see 3 replication slots - 1 for each of 3 remote nodes.
So far so good.

Last week I tried initializing the second database for BDR.  On the donor node I ran `bdr.bdr_group_create`, and then ran `bdr.bdr_group_join` on each of the other nodes.  I monitor with the same SQL, and see 6 replication slots - 1 per database per remote node.  After some period of time, maybe 2 hours at the most, I see the slots drop down to 3 - only those for the database cloned with `bdr_init_copy`. At this point, BDR replication is broken on the second database - no DDL will finish, and I don't get the global DDL lock error message - the DDL statement just hangs forever.  The DDL statement is a dead-simple `CREATE TABLE moo (oink int);`

I thought maybe I'd done something bad whilst doing some cleanup of other things, so today I dropped and recreated the second database in the same fashion, and then made sure to leave things alone.  Again, after a few hours, the replication slots have dropped off and DDL statements just hang.

In the error logs, I see entries like this every few seconds:

```
2016-05-04 19:57:42 UTC [31779]: [1705-1] user=,db=, hostname=LOG:  starting background worker process "bdr (6278758658547617954,5,18610707,)->bdr (6278758653314575602"
2016-05-04 19:57:42 UTC [38403]: [1-1] user=,db=, hostname=ERROR:  tuple natts mismatch, 4 vs 5
2016-05-04 19:57:42 UTC [31779]: [1706-1] user=,db=, hostname=LOG:  worker process: bdr (6278758658547617954,5,18610707,)->bdr (6278758653314575602 (PID 38403) exited with exit code 1
```

**Comment by ringerc** [comment] 2016-05-05 00:11
This is a duplicate of issue #113, see it and its related issues.

It's fixed in git master. We're working on a new release due in a month or so.

**Closed** 2016-05-05 00:13 UTC
