### ISSUE TITLE
bdr_init_copy failed

### ISSUE THREAD

**Issue by aven92** [2ndQuadrant/bdr#61] opened 2015-04-20 10:29 UTC
First, I run the pg_basebackup:
```
/opt/pg94-bdr/bin/pg_basebackup  -h node1 -p 1432  -X stream -D bdr-data
WARNING:  skipping special file "./postgresql.conf"
```
and then when I execute bdr_init_copy like this:
```
/opt/pg94-bdr/bin/bdr_init_copy -d "host=node1 dbname=bdr port=1432" --local-dbname="host=node2 dbname=bdr port=1432" -n node2 -D bdr-data
```
it's blocked:
```
bdr_init_copy: starting ...
Getting remote server identification ...
Detected 1 BDR database(s) on remote server
Updating BDR configuration on the remote node:
 bdr: validating BDR configuration ...
 bdr: creating replication slot ...
 bdr: creating node entry for local node ...
Creating restore point on remote node ...
Bringing local node to the restore point ...
```

**Comment by ringerc** [comment] 2015-04-20 12:13
What operating system and version is this? How did you install BDR, and what BDR version exactly?

It says `skipping special file "./postgresql.conf"`. Please show `ls -ld /path/to/data/directory/postgresql.conf` and `lsattr /path/to/data/directory/postgresql.conf`

**Comment by aven92** [comment] 2015-04-21 03:55
Thank you for the response !
The bdr version is 0.9.0.3, I complie it from source code.
```
psql (9.4.1)
Type "help" for help.

bdr=# \dx
                           List of installed extensions
    Name    | Version |   Schema   |                  Description                  
------------+---------+------------+-----------------------------------------------
 bdr        | 0.9.0.3 | pg_catalog | Bi-directional replication for PostgreSQL
 btree_gist | 1.0     | public     | support for indexing common datatypes in GiST
 plpgsql    | 1.0     | pg_catalog | PL/pgSQL procedural language
(3 rows)
```
The postgresql.conf is this:
```
$ ls -ld postgresql.conf 
lrwxrwxrwx 1 postgres postgres 19 Apr 20 17:54 postgresql.conf -> postgresql.bdr.conf
$ ls -ld postgresql.bdr.conf 
-rw-r--r-- 1 postgres postgres 1159 Apr 20 17:54 postgresql.bdr.conf
$ lsattr postgresql.bdr.conf 
-------------e- postgresql.bdr.conf
```

**Comment by ringerc** [comment] 2015-04-21 05:08
Why did you symlink `postgresql.conf` to `postgresql.bdr.conf` ?

Just do it the usual way, leave `postgresql.conf` in place as a normal file.

**Comment by aven92** [comment] 2015-04-21 07:07
As you see, I redo the pg_basebackup and bdr_init_copy and I remove the symlink, but the problem still there.
```
$ ll -d postgresql.conf 
-rw-r--r-- 1 postgres postgres 1159 Apr 21 15:01 postgresql.conf
$ lsattr postgresql.conf 
-------------e- postgresql.conf
```
The replication_slot like this:
```
bdr=# select * from pg_replication_slots ;
                slot_name                | plugin | slot_type | datoid | database | active | xmin | catalog_xmin | restart_lsn 
-----------------------------------------+--------+-----------+--------+----------+--------+------+--------------+-------------
 bdr_16384_6140083912082363090_2_16384__ | bdr    | logical   |  16384 | bdr      | f      |      |         1831 | 0/5000060
(1 rows)
```
```
bdr=# select * from bdr.bdr_nodes ;
     node_sysid      | node_timeline | node_dboid | node_status | node_name |                     node_local_dsn                     |                   node_init_from_dsn                   
---------------------+---------------+------------+-------------+-----------+--------------------------------------------------------+--------------------------------------------------------
 6139739409922254460 |             1 |      16384 | r           | test1     | host=node1 dbname=bdr port=1432               | 
 6140083912082363090 |             2 |      16384 | c           |           |                                                        | dbname=bdr host=node1 port=1432
(1 rows)
```

**Comment by ringerc** [comment] 2015-04-21 09:24
Odd.

Please show relevant logs from both nodes, as a github   gist (gist.github.com).

Is there anything unusual about your setup?

If that doesn't tell me anything useful, then to proceed I'll really need complete instructions to reproduce the issue on a new clean install, since needless to say it doesn't happen in the automated tests or in my local manual testing. There's not tons I further I can do without being able to reproduce this, and I have some urgent work for paid customers that I have to put first.

**Comment by aven92** [comment] 2015-04-21 09:53
Thanks to answer me from busy time.
the exactly bdr version is:
```
bdr=# SELECT bdr.bdr_version();
    bdr_version    
-------------------
 0.9.0-2015-03-27-
(1 row)
```

It's doesn't have any log in the  node1 and new node, just show some thing like this and block all the time
```
step 1: 
$  /opt/pg94-bdr/bin/pg_basebackup  -h node1_ip -p 1432  -X stream -D .
WARNING:  skipping special file "./postgresql.conf"
step 2:
cp postgresql.bdr.conf postgresql.conf
step 3:
$ /opt/pg94-bdr/bin/bdr_init_copy -d "host=node1_ip dbname=bdr port=1432" --local-dbname="host=node2_ip dbname=bdr port=2432" -n node2 -D .
bdr_init_copy: starting ...
Getting remote server identification ...
Detected 1 BDR database(s) on remote server
Updating BDR configuration on the remote node:
 bdr: validating BDR configuration ...
 bdr: creating replication slot ...
 bdr: creating node entry for local node ...
Creating restore point on remote node ...
Bringing local node to the restore point ...
```

**Comment by ringerc** [comment] 2015-04-21 09:59
> WARNING: skipping special file "./postgresql.conf"

This should not be happening.

Fix your config *before* the basebackup.

Generally, if you get a WARNING, there's a reason for that.


​

**Comment by aven92** [comment] 2015-04-21 10:34
I ignore it because it  work on version 0.8.7, and I fixed it, then problem still there.
Is the physical clone setup right below ?
```
1. /opt/pg94-bdr/bin/pg_basebackup  -h node1_ip -p 1432  -X stream -D bdr-data
2./opt/pg94-bdr/bin/bdr_init_copy -d "host=node1_ip dbname=bdr port=1432" --local-dbname="host=node2_ip dbname=bdr port=2432" -n node2 -D bdr-data
```

**Comment by ringerc** [comment] 2015-04-21 10:46
Aha, the issue is the dbname 'bdr'.

That's reserved by 0.9.0. In retrospect a very poor choice of name, and
0.9.1 will change it to something like `_bdr_supervisordb`.

In the mean time, use a different database name.

**Comment by ringerc** [comment] 2015-04-21 10:58
I just pushed a dbname change to bdr-plugin/REL0_9_0_STABLE and
bdr-plugin/next .

**Comment by aven92** [comment] 2015-04-21 10:58
I change the dbname to 'test' and still blocked.

```
$ /opt/pg94-bdr/bin/bdr_init_copy -d "host=node1_ip dbname=test port=1432" --local-dbname="host=node2_ip dbname=test port=1432" -n test2 -D .
bdr_init_copy: starting ...
Getting remote server identification ...
Detected 2 BDR database(s) on remote server
Updating BDR configuration on the remote node:
 bdr: validating BDR configuration ...
 bdr: creating replication slot ...
 bdr: creating node entry for local node ...
 test: validating BDR configuration ...
 test: creating replication slot ...
 test: creating node entry for local node ...
Creating restore point on remote node ...
Bringing local node to the restore point ...
Transaction log reset
Initializing BDR on the local node:
```

**Comment by ringerc** [comment] 2015-04-21 11:17
Ok, then I'll need *complete, step-by-step information on how to make this happen* from a clean install.

**Comment by aven92** [comment] 2015-04-21 13:42
The first node:
```
test=# create extension btree_gist;
test=# create extension bdr;
test=# SELECT bdr.bdr_group_create(
  local_node_name := 'node1',
  node_external_dsn := 'host=node1_ip dbname=test port=1432'
);
```
The second node:
```
$ /opt/pg94-bdr/bin/pg_basebackup  -h node1_ip -p 1432  -X stream -D bdr-data
$ /opt/pg94-bdr/bin/bdr_init_copy -d "host=node1_ip dbname=test port=1432" --local-dbname="host=node2_ip dbname=test port=1432" -n test2 -D  bdr-data
```

Then blocked:
```
bdr_init_copy: starting ...
Getting remote server identification ...
Detected 2 BDR database(s) on remote server
Updating BDR configuration on the remote node:
 bdr: validating BDR configuration ...
 bdr: creating replication slot ...
 bdr: creating node entry for local node ...
 test: validating BDR configuration ...
 test: creating replication slot ...
 test: creating node entry for local node ...
Creating restore point on remote node ...
Bringing local node to the restore point ...
Transaction log reset
Initializing BDR on the local node:
```

**Comment by ringerc** [comment] 2015-04-24 04:42
OK, we've seen this internally now, and it's fixed in bdr-plugin/next. I'll backport a patch to bdr-plugin/REL0_9_STABLE and it'll appear in the next patch release.

As a workaround in the mean time, you can use an IP address instead of hostname, if it's the same issue I'm seeing here.

**Comment by ringerc** [comment] 2015-04-24 04:54
Backported and pushed to bdr-plugin/REL0_9_STABLE

**Closed by ringerc** 2015-04-24 04:54 UTC
Labels: bug

**Comment by aven92** [comment] 2015-04-25 09:47
Thank you very much!!!
The node1_ip is meaning the ip of the server,  I didn't use the hostname, and really thx a lot!

**Comment by SoumitraBhandary** [comment] 2018-09-14 06:13
Hi , 
I am getting below error while executing bdr_init_copy with -s option and it is failing .  BDR version is 1.0.3 and Postgres Version is 9.4 .
 I have tried also without -s option , there it also some time fails and reports similar error . 
What I can find from Postgres log file during this time that some external connection exists (mostly from the peer node) and it fails to stop the service and keeps on reporting "FATAL:  the database system is shutting down"




bdr_init_copy Error Log :
Transaction log reset
Initializing BDR on the local node:
 db1: adding the database to BDR cluster ...
 db2: adding the database to BDR cluster ...
 db3: adding the database to BDR cluster ...
 db4: adding the database to BDR cluster ...
 db5: adding the database to BDR cluster ...
 db6: adding the database to BDR cluster ...
Stopping the local node ...
pg_ctl: server does not shut down
HINT: The "-m fast" option immediately disconnects sessions rather than
waiting for session-initiated disconnection.
Stopping postgres after successful join failed with 1. See bdr_init_copy_postgres.log.pg_ctl: server does not shut down
HINT: The "-m fast" option immediately disconnects sessions rather than
waiting for session-initiated disconnection.
error:
09-14-2018 05:24:26 [INFO ] => CMD Out - -1
09-14-2018 05:24:26 [ERROR] => Failed to execute source /opt/pgsql/bin/bdr_init_copy -D /PostgresData/data -n <hostname> -d 'host=<hostname_remotenode> port=5432 dbname=db1' -U postgres --local-dbname='host=<localnode_IP> port=5432 dbname=db1' -s

Thanks, 
Soumitra

**Comment by ringerc** [comment] 2018-09-17 08:57
On Fri, 14 Sep 2018 at 14:13, SoumitraBhandary <notifications@github.com>
wrote:

> Hi ,
> I am getting below error while executing bdr_init_copy with -s option and
> it is failing . BDR version is 1.0.3 and Postgres Version is 9.4 .
>
>
> It it necessary for you to provide a full list of the steps you took and
exact commands to get help, really.

Please also show the log file produced by bdr_init_copy. It's in the same
directory as you run bdr_init_copy.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by ringerc** [comment] 2018-09-18 02:54
On Mon, 17 Sep 2018 at 17:22, SoumitraBhandary <notifications@github.com>
wrote:

> Hi ,
>
> Steps performed :
> 1: Create BDR Configuration in remote node
> CREATE EXTENSION btree_gist;
> CREATE EXTENSION bdr;
> SELECT bdr.bdr_group_create( local_node_name := '<Local_Host_name>',
> node_external_dsn := 'host=<Local_FQDN> port=5432 dbname=');
> 2. Stop Postgre service using sytemctl in local node
> 3. Remove files from PGADATA directory in local Node.
> 4. Execute bdr_init_copy in local node source as remote node .
> Command used 👍
> /opt/pgsql/bin/bdr_init_copy -D /PostgresData/data -n local_hostaname -d
> 'host=remote_host port=5432 dbname=db1' -U postgres
> --local-dbname='host=local_ip port=5432 dbname=db1' -s
>
> BDR_INIT_COPY Log 👍
> 2018-09-14 05:24:26.431 GMT--32171 LOG: redirecting log output to logging
> collector process
> 2018-09-14 05:24:26.431 GMT--32171 HINT: Future log output will appear in
> directory "/DGlogs/Postgres_Logs".
> 2018-09-14 05:24:26.631 GMT--32205 LOG: registering background worker "bdr
> supervisor"
> 2018-09-14 05:24:26.706 GMT--32205 LOG: redirecting log output to logging
> collector process
> 2018-09-14 05:24:26.706 GMT--32205 HINT: Future log output will appear in
> directory "/DGlogs/Postgres_Logs"
>
>
> ... and what's in "the future log output" dir?

Show or attach complete logs please.


-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by SoumitraBhandary** [comment] 2018-09-18 05:51
Entire postgres Log was filled with this message : I verified BDR_NODES view in remote node , it contained both entry for remote and local . But remote node i.e. in which BDR_INIT_COPY was executed it was in connecting state and not turned to ready state . 


Postgres Log >>

2018-09-14 05:24:26 GMT-[unknown]-11212 LOG:  connection received: host=peer_node_ip port=46756
	2018-09-14 05:24:26 GMT-[unknown]-11213 LOG:  connection received: host=peer_node_ip port=51372
	2018-09-14 05:24:26 GMT-idap_prod-11213 FATAL:  the database system is starting up

	2018-09-14 05:24:26 GMT-idap_prod-20297 FATAL:  the database system is shutting down
	2018-09-14 05:24:26 GMT-[unknown]-20298 LOG:  connection received: host=peer_node_ip port=60424
