### ISSUE TITLE
Database locked against DDL operations doesn't allow DML ones, either

### ISSUE THREAD

**Issue by fvanderelst** [2ndQuadrant/bdr#159] opened 2016-01-18 17:23 UTC
Hello

What great software !  Praise Praise !

I found the following, and was not expecting it.  On Postgres DBR 9.4.5 with 4 nodes, I do, on node 0:

\# DROP INDEX pk_mega_index;
DROP INDEX
Time: 196635.233 ms

There's not much other activity (see below).

It's a big index.  First (minor) question, is why does this take 169 seconds ?

The second, bigger one, is as follows.

There's a table named current_load, primary key server_name, each of the 4 nodes is running a script issuing an update against its own server_name.  On 4 other windows, I run a continuous select showing me the timestamp lag.  Normally they're 0.1  - 0.2s behind, like so ('lag' means now() - tstamp):

```
 server_name |            tstamp             |    lag   
-------------+-------------------------------+-----------+---------
 pg9-50      | 2016-01-18 17:09:27.84364+00  |      0.15 
 pg9-51      | 2016-01-18 17:09:27.822943+00 |      0.17
 pg9-52      | 2016-01-18 17:09:27.93993+00  |      0.05 
 pg9-53      | 2016-01-18 17:09:27.853865+00 |      0.14
```

However, **while** the DROP TABLE is happening, everything falls very far behind 140 - 200s, I've seen much longer):

```
 server_name |            tstamp             |    lag 
-------------+-------------------------------+-----------+---------
 pg9-50      | 2016-01-18 16:38:49.775729+00 |    208.92 
 pg9-51      | 2016-01-18 16:39:53.782387+00 |    144.92 
 pg9-52      | 2016-01-18 16:39:56.875296+00 |    141.82 
 pg9-53      | 2016-01-18 16:39:38.200254+00 |    160.50 
```

I don't think the replication is stopping.

The updates to this table are stopping on all 4 nodes.

The logs on the 4 nodes show:

```
 2016-01-18 16:51:53 GMT mf ref STATEMENT:
                 update current_load
                    set tstamp = current_timestamp
                        ,uptime = '10 days, 21:28'
                        ,nb_users = '5'
                        ,ld_1min = '0.56'
                        ,ld_5min = '0.76'
                        ,ld_15min = '0.89'
                  where server_name = 'pg9-50'
 2016-01-18 16:51:54 GMT mf ref ERROR:  Database is locked against DDL operations
 2016-01-18 16:51:54 GMT mf ref HINT:  Node (6238905362961380958,1,16385) in the cluster is already performing DDL
 2016-01-18 16:51:54 GMT mf ref STATEMENT:
                 update current_load
                    set tstamp = current_timestamp
                        ,uptime = '10 days, 21:28'
                        ,nb_users = '5'
                        ,ld_1min = '0.56'
                        ,ld_5min = '0.76'
                        ,ld_15min = '0.89'
                  where server_name = 'pg9-50'
 2016-01-18 16:51:54 GMT mf ref ERROR:  Database is locked against DDL operations
 2016-01-18 16:51:54 GMT mf ref HINT:  Node (6238905362961380958,1,16385) in the cluster is already perfor
...
```

The odd thing is, this is not a DDL operation.  It's a Data Modification (DML) operation; so while I'd understand an ALTER TABLE getting delayed, I don't think an UPDATE should be prevented.

This is a straight table with primary key on server_name, there are no triggers.

Am I mistaken to think UPDATE operations should continue even if there's some DML happening elsewhere (different table, schema, etc) ?

Many thanks

Freddie Vander Elst

**Comment by fvanderelst** [comment] 2016-01-18 17:28
As a follow-up, when the DROP INDEX finishes, the UPDATE statements work and everything synchronises right away (which is great).

But it does mean that the entire cluster freezes for 169s.

If I ALTER TABLE xxx ADD PRIMARY KEY, or, CREATE INDEX .. the same happens.  No DML anywhere else.

This is a spanner in my High-Availability plans... :anguished:

Fve

**Comment by ringerc** [comment] 2016-01-20 04:28
This is by design.

"Locked against DDL" is a bit misleading I think. It means that  DDL that
required a global DDL lock is stopping all write operations. The DB is
locked due to DDL. It's necessary to do this because otherwise committed
xacts that modify a table might modify the old version and the xact might
not replay correctly on nodes that've changed the table definition.

The next major revision of BDR tries to make the locks more specific to the
affected objects, but to do this really well we need support for logical
decoding of prepared 2 phase transactions. That's not available in
PostgreSQL at the moment. So we're a bit limited and can mainly just limit
locks for certain operations that affect only one table.

In the end though doing schema changes is always going to hurt. You can
disable DDL replication and DDL locking then run the DML manually on each
node, but in that case if you break it you get to keep the pieces ;) .

**Comment by ringerc** [comment] 2016-01-20 04:29
The current bdr-plugin/next also reduces the impact of DDL locking by
avoiding cancelling queries where possible. It tries to let queries block
until DDL completes instead.

**Comment by ringerc** [comment] 2016-01-20 04:32
I'm inclined to close this. There's work in progress on DDL locking, it's a known issue, and mainly needs docs improvements.

**Comment by PJMODOS** [comment] 2016-02-10 07:14
I think this mainly needs the #160 otherwise it's by design so nothing to do here.

**Closed by PJMODOS** 2016-02-10 07:14 UTC
Labels: ddl-replication, question
