### ISSUE TITLE
CREATE SEQUENCE followed by OWNER TO hangs

### ISSUE THREAD

**Issue by agx** [2ndQuadrant/bdr#64] opened 2015-04-30 17:09 UTC
Hi,
I'm currently trying trying to import the Foreman database into bdr. After dumping it and changing the sequence type to bdr like (for all table):

```
CREATE TABLE bug_architectures (
    id integer NOT NULL,
    name character varying(255) DEFAULT NULL::character varying NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    hosts_count integer DEFAULT 0,
    hostgroups_count integer DEFAULT 0
);
ALTER TABLE bug_architectures OWNER TO foreman;


CREATE SEQUENCE bug_architectures_id_seq
    USING bdr;
ALTER TABLE bug_architectures_id_seq OWNER TO foreman;
ALTER SEQUENCE bug_architectures_id_seq OWNED BY architectures.id;
```

I can reproducibly hang a 'psql test3 < dump.sql' on the first OWNER change of the first sequene. If I cancel that one it proceeds and hangs at the next one. _But_ if I take out all OWNER changes and move them to a separate script and apply them after some seconds everything is fine. In  the hang case I see:

```
postgres=# select * from pg_stat_activity WHERE datname='test3';
 datid | datname | pid  | usesysid | usename  |              application_name              |  client_addr  | client_hostname | client_port |         backend_start         |          xact_start           |
+query_start          |         state_change          | waiting | state  | backend_xid | backend_xmin |                                             query
-------+---------+------+----------+----------+--------------------------------------------+---------------+-----------------+-------------+-------------------------------+-------------------------------+-------
+------------------------+-------------------------------+---------+--------+-------------+--------------+------------------------------------------------------------------------------------------------
 22389 | test3   | 6193 |       10 | postgres | bdr (6143134531729040619,1,22389,): perdb  |               |                 |             | 2015-04-30 14:59:18.87812+02  | 2015-04-30 15:07:16.661488+02 | 2015-0
+4-30 15:09:42.720388+02 | 2015-04-30 15:09:42.720389+02 | t       | active |             |         5836 | start_elections
 22389 | test3   | 6783 |       10 | postgres | psql                                       |               |                 |          -1 | 2015-04-30 15:09:41.789485+02 | 2015-04-30 15:09:42.730681+02 | 2015-0
+4-30 15:09:42.730681+02 | 2015-04-30 15:09:42.730684+02 | f       | active |        5836 |         5836 | ALTER TABLE bug_architectures_id_seq OWNER TO foreman;
 22389 | test3   | 6210 |       10 | postgres | bdr (6143134531729040619,1,22389,): apply  |               |                 |             | 2015-04-30 14:59:34.140134+02 | 2015-04-30 14:59:34.139366+02 | 2015-0
+4-30 14:59:34.139366+02 | 2015-04-30 15:09:42.745072+02 | t       | active |             |              | bdr_apply: BEGIN origin(source, orig_lsn, timestamp): 0/4ED17F0, 2015-04-30 15:09:42.725165+02
 22389 | test3   | 6209 |       10 | postgres | bdr (6143123558799401289,1,22356,):receive | 10.205.55.104 |                 |       49077 | 2015-04-30 14:59:34.140409+02 |                               |
+| 2015-04-30 14:59:34.145833+02 | f       | idle   |             |              |
(4 rows)
```

on the first node that runs the import and on the second:

```
test3=# select * from pg_stat_activity where datname='test3';
 datid | datname |  pid  | usesysid | usename  |             application_name              | client_addr | client_hostname | client_port |         backend_start         |          xact_start           |
+query_start          |         state_change          | waiting | state  | backend_xid | backend_xmin |                                             query
-------+---------+-------+----------+----------+-------------------------------------------+-------------+-----------------+-------------+-------------------------------+-------------------------------+---------
+----------------------+-------------------------------+---------+--------+-------------+--------------+------------------------------------------------------------------------------------------------
 22356 | test3   | 31464 |       10 | postgres | psql                                      |             |                 |          -1 | 2015-04-30 14:58:43.522683+02 | 2015-04-30 15:11:44.429621+02 | 2015-04-
+30 15:11:44.429621+02 | 2015-04-30 15:11:44.429627+02 | f       | active |             |        14887 | select * from pg_stat_activity where datname='test3';
 22356 | test3   | 31742 |       10 | postgres | bdr (6143123558799401289,1,22356,): perdb |             |                 |             | 2015-04-30 15:04:15.50573+02  |                               | 2015-04-
+30 15:09:42.740142+02 | 2015-04-30 15:09:42.740492+02 | f       | idle   |             |              | get_chunk
 22356 | test3   | 31506 |       10 | postgres | bdr (6143123558799401289,1,22356,): apply |             |                 |             | 2015-04-30 14:59:34.127722+02 |                               | 2015-04-
+30 14:59:34.126665+02 | 2015-04-30 15:09:42.722663+02 | f       | idle   |             |              | bdr_apply: BEGIN origin(source, orig_lsn, timestamp): 0/4B6C090, 2015-04-30 15:09:42.713372+02
(3 rows)
```

I'm currently using these packages:

postgresql-bdr94-2ndquadrant-redhat-1.0-2.noarch
postgresql-bdr94-9.4.1_bdr2-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-bdr-0.9.0-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-contrib-9.4.1_bdr2-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-libs-9.4.1_bdr2-1_2ndQuadrant.el6.x86_64
postgresql-bdr94-server-9.4.1_bdr2-1_2ndQuadrant.el6.x86_64

Anything I can provide to debug this further?

**Comment by alvherre** [comment] 2015-04-30 19:41
The catalog bdr.bdr_queued_commands should contain the commands as they are sent to the remote servers for replication. Can you eyeball the contents and see if anything is amiss?  If there's a bug in DDL deparsing, it would probably show up as something that has a different effect in the remote servers, or even as an invalid command.

**Comment by kforte90** [comment] 2015-04-30 20:25
Here's the repro I ran on a two-node cluster enabled with BDR:
bdrdemo=# create user foreman;
CREATE ROLE
bdrdemo=# CREATE TABLE bug_architectures (
bdrdemo(#     id integer NOT NULL,
bdrdemo(#     name character varying(255) DEFAULT NULL::character varying NOT NULL,
bdrdemo(#     created_at timestamp without time zone NOT NULL,
bdrdemo(#     updated_at timestamp without time zone NOT NULL,
bdrdemo(#     hosts_count integer DEFAULT 0,
bdrdemo(#     hostgroups_count integer DEFAULT 0
bdrdemo(# );
CREATE TABLE
bdrdemo=# ALTER TABLE bug_architectures OWNER TO foreman;
ALTER TABLE
bdrdemo=# 
bdrdemo=# 
bdrdemo=# CREATE SEQUENCE bug_architectures_id_seq
bdrdemo-#     USING bdr; -- hanging, as user described

In this case, as noted above, the user 'foreman' was only created on one node.  Therefore, when the user issued 'ALTER TABLE bug_architectures OWNER TO foreman;'  the command couldn't find the 'foreman' user on one of the nodes.  Subsequently, the next DDL command hung.  
Since global DDL such as 'CREATE USER' isn't replicated, there is a BDR function that you can call to replicate global DDL: ‘SELECT bdr_replicate_ddl_command ('CREATE USER foreman');'

**Comment by scherrey** [comment] 2015-05-01 15:12
Are you sure this isn't a copy of issue #4 https://github.com/2ndQuadrant/bdr/issues/4 ? Looks identical at first glance.

**Comment by agx** [comment] 2015-05-01 18:05
On Fri, May 01, 2015 at 08:12:03AM -0700, Ben Scherreys wrote:
> Are you sure this isn't a copy of issue #4 https://github.com/2ndQuadrant/bdr/issues/4 ? Looks identical at first glance.

This looks quiet similar indeed.
 -- Guido

**Comment by agx** [comment] 2015-05-01 18:07
On Thu, Apr 30, 2015 at 01:25:45PM -0700, kforte90 wrote:
> Here's the repro I ran on a two-node cluster enabled with BDR:
> bdrdemo=# create user foreman;
> CREATE ROLE
> bdrdemo=# CREATE TABLE bug_architectures (
> bdrdemo(#     id integer NOT NULL,
> bdrdemo(#     name character varying(255) DEFAULT NULL::character varying NOT NULL,
> bdrdemo(#     created_at timestamp without time zone NOT NULL,
> bdrdemo(#     updated_at timestamp without time zone NOT NULL,
> bdrdemo(#     hosts_count integer DEFAULT 0,
> bdrdemo(#     hostgroups_count integer DEFAULT 0
> bdrdemo(# );
> CREATE TABLE
> bdrdemo=# ALTER TABLE bug_architectures OWNER TO foreman;
> ALTER TABLE
> bdrdemo=# 
> bdrdemo=# 
> bdrdemo=# CREATE SEQUENCE bug_architectures_id_seq
> bdrdemo-#     USING bdr; -- hanging, as user described
> 
> In this case, as noted above, the user 'foreman' was only created on one node.  Therefore, when the user issued 'ALTER TABLE bug_architectures OWNER TO foreman;'  the command couldn't find the 'foreman' user on one of the nodes.  Subsequently, the next DDL command hung.  
> Since global DDL such as 'CREATE USER' isn't replicated, there is a BDR function that you can call to replicate global DDL: ‘SELECT bdr_replicate_ddl_command ('CREATE USER foreman');'

I have created the user on both sides via "CREATE ROLE foreman". Sorry
for not mentioning this.
Cheers,
 -- Guido

**Comment by agx** [comment] 2015-05-04 16:11
On Thu, Apr 30, 2015 at 12:41:13PM -0700, Alvaro Herrera wrote:
> The catalog bdr.bdr_queued_commands should contain the commands as they are sent to the remote servers for replication. Can you eyeball the contents and see if anything is amiss?  If there's a bug in DDL deparsing, it would probably show up as something that has a different effect in the remote servers, or even as an invalid command.

Here you go:

```
test10=# select * from bdr.bdr_queued_commands;
    lsn    |           queued_at           | perpetrator |   command_tag    |                                                                                                                                                                                       command                                                                                                                                                                                       
-----------+-------------------------------+-------------+------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 0/6648000 | 2015-05-04 17:57:55.552915+02 | postgres    | CREATE EXTENSION | CREATE EXTENSION  bdr SCHEMA pg_catalog
 0/6674730 | 2015-05-04 17:58:31.56918+02  | postgres    | SELECT           | SELECT bdr.bdr_connections_changed()
 0/6690E20 | 2015-05-04 17:59:50.775841+02 | postgres    | COMMENT          | COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language'
 0/6691088 | 2015-05-04 17:59:50.783485+02 | postgres    | CREATE TABLE     | CREATE  TABLE  public.bug_architectures (id pg_catalog.int4  NOT NULL , name pg_catalog."varchar"(255) DEFAULT NULL::character varying NOT NULL COLLATE pg_catalog."default", created_at pg_catalog."timestamp"  NOT NULL , updated_at pg_catalog."timestamp"  NOT NULL , hosts_count pg_catalog.int4 DEFAULT 0  , hostgroups_count pg_catalog.int4 DEFAULT 0  )  WITH (oids=OFF)  
 0/6691088 | 2015-05-04 17:59:50.783485+02 | postgres    | CREATE TRIGGER   | CREATE  TRIGGER truncate_trigger AFTER TRUNCATE ON public.bug_architectures   FOR EACH STATEMENT  EXECUTE PROCEDURE bdr.queue_truncate()
 0/6694770 | 2015-05-04 17:59:51.025175+02 | postgres    | ALTER TABLE      | ALTER TABLE  public.bug_architectures OWNER TO foreman
 0/6698890 | 2015-05-04 17:59:51.483309+02 | postgres    | CREATE SEQUENCE  | CREATE  SEQUENCE public.bug_architectures_id_seq CACHE 1 NO CYCLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 RESTART 1 USING bdr
(7 rows)
```

I can't spot anything obviously wrong here. Let me know if I can provide
further info.
Cheers,
 -- Guido

**Comment by anarazel** [comment] 2015-05-25 00:17
I've seen something similar in the past. But I now tried to reproduce this with various scenarios, and I can't anymore. I see a potentially problematic scenario, which I'm going to fix. But given I can't reproduce the problem anymore, I can't guarantee it's this problem.

Any chance you could check whether the issue still occurs with /next? And if so, try to describe your setup in a bit more detail?

**Comment by ringerc** [comment] 2015-05-26 08:32
Is this the same as #52 ?

**Comment by PJMODOS** [comment] 2015-06-29 19:19
This is same as #4 and I can't reproduce it anymore either, so closing.

**Closed by PJMODOS** 2015-06-29 19:19 UTC
