### ISSUE TITLE
Unable to install BDR if a constraint is violated

### ISSUE THREAD

**Issue by sym39** [2ndQuadrant/bdr#165] opened 2016-03-04 10:17 UTC
# How to reproduce 

BDR version 0.9.3.

Have a foreign key constraint that is not respected.
I do not know really how I went in this situation. I was unable to reproduce it.

The following tables are:
```
mydb=# \d datas
Table "datas"
    Column     |  Type   | Modifiers 
---------------+---------+-----------
 info_id     | integer | not null
 time          | bigint  | not null
 [...]
Indexes:
    "datas_pkey" PRIMARY KEY, btree (info_id, "time")
[...]
Foreign-key constraints:
    "datas_info_id_fkey" FOREIGN KEY (info_id) REFERENCES infos(id)

mydb=# \d infos
Table "infos"
     Column      |  Type   |                                Modifiers                                
-----------------+---------+-------------------------------------------------------------------------
 id              | integer | not null default nextval('infos_id_seq'::regclass)
[...]
Indexes:
    "infos_pkey" PRIMARY KEY, btree (id)
Referenced by:
    TABLE "datas" CONSTRAINT "datas_info_id_fkey" FOREIGN KEY (info_id) REFERENCES infos(id)
[...]

```

Next are the postgres logs when the problem appears: 
```
postgres warning [2640]: [1936-1] ERROR:  insert or update on table "datas" violates foreign key constraint "datas_info_id_fkey"
postgres warning [2640]: [1936-2] DETAIL:  Key (info_id)=(18) is not present in table "infos".
[...]
postgres error [1755]: [17-1] FATAL:  bdr: /usr/lib/postgresql/9.4/bin/bdr_initial_load exited with exit code 2
[...]
postgres warning [6097]: [19-1] ERROR:  previous init failed, manual cleanup is required 
```

# Workaround 
Solve the constraint by deleting orphan data tuples, clean the remote node and join the 2 nodes again.

# Question
Is it a way to force the BDR installation in such case? If not, is it a simple way to check for database correctness and to find issues before trying to install BDR?

Thanks and regards,
Sylvain

**Comment by ringerc** [comment] 2016-03-18 03:01
Is the FK present and correct on the master node?

Are you using replication sets?

What commands exactly did you use for setup?

I think this needs to be reproduced before we can really do anything. That said, I think our handling of foreign keys is definitely problematic, and it's pretty much broken when it comes to replication sets.

**Comment by sym39** [comment] 2016-03-18 14:12
In my case, I did not use replication sets, I guess the source node was problematic, before installing BDR, but I don't know how I came in that situation (may be a previous installation of BDR broke the source node because multiple nodes were writting the same keys on different nodes (I should not say that, you will kill me ...). 

It is possible to reproduce this problem I had by enforcing a constraint to be violated like this:

# Node 1 (10.0.0.1)
```
\c postgres
CREATE DATABASE test TEMPLATE template0;
\c test
CREATE EXTENSION btree_gist;
CREATE EXTENSION bdr;
CREATE TABLE datas (id INT PRIMARY KEY, info_id INT);
CREATE TABLE infos (info_id INT PRIMARY KEY);        
ALTER TABLE datas ADD CONSTRAINT datas_info_id_fkey FOREIGN KEY (info_id) REFERENCES infos (info_id);
ALTER TABLE datas DISABLE TRIGGER ALL ;
INSERT INTO datas VALUES (1,1);
ALTER TABLE datas ENABLE TRIGGER ALL ;
SELECT bdr.bdr_group_create(local_node_name := 'node1',node_external_dsn := 'user=postgres password=postgres host=10.0.0.1 port=5432 dbname=test');
SELECT bdr.bdr_node_join_wait_for_ready();
```

# Node 2 (10.0.0.2)
```
\c postgres
CREATE DATABASE test TEMPLATE template0;
\c test
CREATE EXTENSION btree_gist;
CREATE EXTENSION bdr;
SELECT bdr.bdr_group_join(local_node_name := 'node2',node_external_dsn := 'user=postgres password=postgres host=10.0.0.2 port=5432 dbname=test', join_using_dsn := 'user=postgres password=postgres host=10.0.0.1 port=5432 dbname=test');
SELECT bdr.bdr_node_join_wait_for_ready();
```

# Log on node2
```
postgres warning [23894]: [348-1] ERROR:  insert or update on table "datas" violates foreign key constraint "datas_info_id_fkey"
postgres warning [23894]: [348-2] DETAIL:  Key (info_id)=(1) is not present in table "infos".
postgres warning [23894]: [348-3] STATEMENT:  ALTER TABLE ONLY datas
postgres error [23753]: [332-1] FATAL:  bdr: /usr/lib/postgresql/9.4/bin/bdr_initial_load exited with exit code 2
```



Thanks you,
Sylvain

**Comment by ringerc** [comment] 2016-03-24 03:12
Yeah. If the FK is violated then this is expected behaviour.

pglogical won't be subject to this since it runs with
session_replication_role = replica .  I'm not sure we can do much about it
in 9.4BDR but it's worth looking into as part of evaluating what we can
include in the next release.

**Comment by PJMODOS** [comment] 2016-05-04 19:02
Duplicte of #171

**Comment by PJMODOS** [comment] 2016-05-05 13:22
Should be fixed in HEAD.

**Closed by PJMODOS** 2016-05-05 13:22 UTC
Labels: duplicate, help wanted
