### ISSUE TITLE
bug when i use UDR subscrib a diff-name database

### ISSUE THREAD

**Issue by digoal** [2ndQuadrant/bdr#130] opened 2015-10-09 16:18 UTC
when upstream dbname not equal to downstream dbname, and downstream node no the upstream's source db , will error:

http://blog.163.com/digoal@126/blog/static/1638770402015998841360/

```
Dumping remote database "hostaddr=127.0.0.1 port=1921 dbname=up user=postgres fallback_application_name='bdr (6203675445083668497,1,16385,): init_replica dump'" with 1 concurrent workers to "pg_bdr_temp_dump_dir/postgres-bdr-000C837A-1.8393"
Restoring dump to local DB "hostaddr=127.0.0.1 port=1922 dbname=down user=postgres fallback_application_name='bdr (6203675445083668497,1,16385,): init_replica restore' options='-c bdr.do_not_replicate=on -c bdr.permit_unsafe_ddl_commands=on -c bdr.skip_ddl_replication=on -c bdr.skip_ddl_locking=on'" with 1 concurrent workers from "pg_bdr_temp_dump_dir/postgres-bdr-000C837A-1.8393"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 3265; 1262 16385 SECURITY LABEL up postgres
pg_restore: [archiver (db)] could not execute query: ERROR:  database "up" does not exist
    Command was: SECURITY LABEL FOR bdr ON DATABASE up IS '{ "bdr" : true }';

```

pg_restore to hostaddr=127.0.0.1 port=1922 dbname=down user=postgres fallback_application_name='bdr (6203675445083668497,1,16385,): init_replica restore' options='-c bdr.do_not_replicate=on -c bdr.permit_unsafe_ddl_commands=on -c bdr.skip_ddl_replication=on -c bdr.skip_ddl_locking=on' failed, aborting

**Comment by ringerc** [comment] 2015-10-12 06:22
This is a known bug, and it comes from an underlying problem with `pg_dump`. 

The workaround at this point is to either use the same DB names, or create an empty database with the same name on the destination. Yes, that's ugly.

I'll need to patch `pg_dump` to fix it, but it's not that simple - because PostgreSQL doesn't have any way to write `SECURITY LABEL FOR bdr ON DATABASE current_database IS ...`.

**Comment by ringerc** [comment] 2015-10-12 06:23
Duplicate of #72

**Closed by ringerc** 2015-10-12 06:23 UTC
Labels: bug, core-change, initialisation
