### ISSUE TITLE
Feature request: bdr_subscribe dry-run mode

### ISSUE THREAD

**Issue by jberkus** [2ndQuadrant/bdr#81] opened 2015-06-02 17:33 UTC
It would be tremendously useful for bdr_subscribe() (and probably other utilities) to have a dry-run mode where it would report any errors with potentially subscribing to a replica set, without actually copying any data.  This would avoid a lot of painful subscribe/unsubscribe action as a user tries to get their connection parameters right.

**Comment by anarazel** [comment] 2015-06-02 19:27
> It would be tremendously useful for bdr_subscribe() (and probably
> other utilities) to have a dry-run mode where it would report any
> errors with potentially subscribing to a replica set, without actually
> copying any data.  This would avoid a lot of painful
> subscribe/unsubscribe action as a user tries to get their connection
> parameters right.

The ones we can determine upfront pretty much all are checked
upfront. Sorry, I can't see this as a priority. The effort seems to be
much better spent elsewhere atm.

**Comment by jberkus** [comment] 2015-06-02 19:41
It currently doesn't check if it can connect to both databases, unless something has been committed in the last week.

**Comment by ringerc** [comment] 2015-06-03 04:30
BDR join does​, at least. Take a look at the BDR join code and compare to
the subscribe logic, it's possible something got missed, but I don't see it
at first glance.

We go to quite a bit of effort to sanity check connection parameters etc,
at least for BDR join, to the point where we even connect to the join
target node, then ask it to connect back to us to validate the external
DSN. That last step makes no sense for UDR, of course, but the rest should
still be done.

Take a look at bdr_subscribe, the latest version is in
extsql/bdr--0.9.0.1--0.9.0.2.sql , and bdr.internal_begin_join, the latest
version of which is in bdr--0.9.0.0--0.9.0.1.sql .

If there's a case we're not checking that's realistic to check, try to
provide steps to reproduce or even better, a patch.

Most of the things that don't get checked aren't checked because we can't
really test them without actually doing them, e.g. the only way we can be
sure we can create a slot or launch a bgworker is by doing it, there's no
reservations system that'd let us claim a resource for later guaranteed
availability.

**Comment by ringerc** [comment] 2015-06-03 04:31
IOW, I think this needs to be more specific. What exactly don't we check that we can realistically check in advance?

**Comment by jberkus** [comment] 2015-06-09 21:13
Craig:

If we fix bug #77, we don't need the dry-run mode.  However, given that presently (a) bdr_subscribe can silently fail and you have to poll the logs to find out why, and (b) you can't undo a fail without some surgery, it's important to have as few bdr_subscribe fails as possible.

Here's two things bdr_subscribe does NOT check for before proceeding with the subscribe, and which it certainly could (at least, as of the last checkout I tried, from the 0.9.1 commit):

1. if it can make a connection to both servers, in both modes (psql and replication)
2. if all tables in the replication set have PKs

Those two things cover about 90% of the failures I had in testing, especially (1).

**Comment by PJMODOS** [comment] 2015-06-09 21:25
I don't think we want to do (2). Tables are not absolutely required to have PK, there are insert only tables in real-world.

**Comment by ringerc** [comment] 2015-06-19 09:30
I'm inclined to issue a `WARNING` for (2). It's fine for them to exist, but we should probably complain about it.

(1) should already be being checked for. I'd like to know specifics about the cases where issues are not detected. See https://github.com/2ndQuadrant/bdr/issues/81#issuecomment-108187149 for details on where these things are checked for.

**Comment by jberkus** [comment] 2015-06-19 13:41
So what I encountered with 0.9.0 was that BDR couldn't connect to the local node because of pg_hba.conf.  By the time it got to this error, it had already set up the remote node, which then had to be cleaned up manually.  If this is supposed to be fixed in 0.9.1, I'll retest.

**Comment by jberkus** [comment] 2015-06-19 13:42
Sorry, specifically that bdr_subscribe couldn't connect.

**Comment by ringerc** [comment] 2015-06-22 04:15
That's odd, as `bdr.bdr_subscribe` invokes `bdr.internal_begin_join`, which calls `bdr_get_remote_nodeinfo(local_node_dsn)` to check that the libpq connection to the downstream exists (for `pg_restore`) and also calls `bdr_get_remote_nodeinfo(remote_dsn)` to check that the connection from downstream to upstream works.

Can you show the exact error message from the logs please? Preferably with `log_verbosity = 'verbose'`.

Hm, I'm not sure I see a check for `remote_dsn` in `replication=database` mode - perhaps that was the issue?

**Comment by jberkus** [comment] 2015-06-22 16:35
I'll retest on 0.9.1 when I actually get home (at another con now)

**Comment by PJMODOS** [comment] 2016-05-04 19:11
closing as UDR is deprecated

**Closed by PJMODOS** 2016-05-04 19:11 UTC
