### ISSUE TITLE
Loading thousands of rows into a table with a BDR sequence from two different nodes causes load to fail

### ISSUE THREAD

**Issue by kforte90** [2ndQuadrant/bdr#53] opened 2015-04-08 21:13 UTC
Adding more multi-user tests to include an initial load from two different nodes.  The load fails with 
```
ERROR:  could not find free sequence value for global sequence public.cust_seq
HINT:  The sequence is refilling from remote nodes. Try again soon. Check that all nodes are up if the condition persists.
```
All nodes are up.  After waiting a bit (a hour and then multiple hours), still could not load tables.  Tried to ALTER the sequence, changing its RESTART and CACHE attributed, but this is not allowed.  Petr commented that there is a fix in the works for this issue.  
Here's the repro:
```
CREATE SEQUENCE cust_seq USING bdr;
CREATE TABLE new_customer (
   new_customer_id  int4 default nextval(' cust_seq') NOT NULL,
   first_name    VARCHAR(10) NOT NULL,
   last_name     VARCHAR(10) NOT NULL,
   date_of_birth DATE                   ,
   phone_number  VARCHAR(10) NOT NULL,
   longfillindata          CHAR(100)             ,
   CONSTRAINT new_customer_pk PRIMARY KEY (new_customer_id)
);
CREATE FUNCTION random_string(minlen NUMERIC, maxlen NUMERIC)
RETURNS VARCHAR(1000)
AS
$$
DECLARE
  rv VARCHAR(1000) := '';
  i  INTEGER := 0;
  len INTEGER := 0;
BEGIN
  IF maxlen < 1 OR minlen < 1 OR maxlen < minlen THEN
    RETURN rv;
  END IF;

  len := floor(random()*(maxlen-minlen)) + minlen;

  FOR i IN 1..floor(len) LOOP
    rv := rv || chr(97+CAST(random() * 25 AS INTEGER));
  END LOOP;
  RETURN rv;
END;
$$ LANGUAGE plpgsql;
```
Now, we load the table with the BDR sequence simultaneously from two nodes:
```
-- node 1
INSERT INTO new_customer (  first_name,
                       last_name,    date_of_birth,
                       phone_number, longfillindata)
SELECT GENERATE_SERIES
     , initcap(lower(random_string(2, 8)))
     , CURRENT_DATE - CAST(floor(random() * 365 * 10 + 40 * 365) AS NUMERIC) * INTERVAL '1 DAY'
     , CAST(floor(random() * 9000 + 1000) AS NUMERIC)
     , 'longfillindata'
  FROM GENERATE_SERIES(1, 50000);

-- run from node 2
INSERT INTO new_customer (  first_name,
                       last_name,    date_of_birth,
                       phone_number, longfillindata)
SELECT GENERATE_SERIES
     , initcap(lower(random_string(2, 8)))
     , CURRENT_DATE - CAST(floor(random() * 365 * 10 + 40 * 365) AS NUMERIC) * INTERVAL '1 DAY'
     , CAST(floor(random() * 9000 + 1000) AS NUMERIC)
     , 'longfillindata'
  FROM GENERATE_SERIES(1, 50000);
```
Both nodes get the following error:
```
ERROR:  could not find free sequence value for global sequence public.cust_seq
HINT:  The sequence is refilling from remote nodes. Try again soon. Check that all nodes are up if the condition persists.
SELECT COUNT(*) FROM new_customer;
 count 
-------
     0
(1 row)
```
The workaround is to re-create the sequence, table and load at this point.  The is part of a multi-user test for BDR sequences.

**Comment by ringerc** [comment] 2015-04-13 06:13
"Petr commented that there is a fix in the works for this issue". Which issue, exactly, and what proposed fix? Do you mean the fact that we can't block on sequence allocations, so:

    ERROR:  could not find free sequence value for global sequence public.cust_seq

is thrown when sequence chunks haven't been assigned yet? If so, yes, that'll be fixed when the 9.5 seqam support is backported into 9.4bdr, a non-trivial task but an important one (#55).

**Comment by ringerc** [comment] 2015-04-13 06:16
It sounds like the issue is:

> The load fails

and that everything after that is knock-on effects.

Can you be more specific about how this 3 (?) node setup was created? In what order was DDL done, node joins executed, etc? Please also supply relevant log excerpts.

**Comment by PJMODOS** [comment] 2015-06-29 19:38
This depends on #56

**Comment by pascalbetz** [comment] 2015-07-24 11:52
@ringerc I've got the same issue. The fact that the read on the sequence is not blocking but raising an exception makes it impossible for me to use BDR at this point. Is the blocking support already implemented in a later version? Any pointers would be appreciated.

**Comment by PJMODOS** [comment] 2016-05-07 15:44
Mostly fixed in HEAD, we'll now wait for the voting to happen, but we will still bail if the voting didn't happen within a minute or statement_timeout whichever is lower.

**Closed by PJMODOS** 2016-05-07 15:44 UTC
Labels: bug

**Comment by ringerc** [comment] 2016-05-08 11:03
On 7 May 2016 at 23:44, Petr Jelinek <notifications@github.com> wrote:

> Mostly fixed in HEAD, we'll now wait for the voting to happen, but we will
> still bail if the voting didn't happen within a minute or statement_timeout
> whichever is lower.
>
>
> Very nice. I didn't think this was even vaguely fixable with the current
sequence access method API in 9.4.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services
