### ISSUE TITLE
Rescue of DDL locks on production nodes network or reserve nodes network

### ISSUE THREAD

**Issue by execut** [2ndQuadrant/bdr#285] opened 2017-03-24 09:42 UTC
Hello! I think to get around this lock, you need to have a mirror network of standby nodes. At the time of locking, all applications switch to it. To raise them there are several exits:
1. Periodically make a copy of the database and take backup copies of all nodes. Here the drawback is that the mirrors are irrelevant and you can not apply the changes back.
2. Stream replication from one node network to another. This, as I understood, can not be done because of the fact that each BDR node is operating in a logical mode, but for streaming replication wal_level = hot_standby is needed.

Maybe you can tell me what to do so that the work of applications is not blocked while due to changes in structure of database?

**Comment by ringerc** [comment] 2017-03-24 10:04
I'm confused. Is this meant to a be a bug report or feature request?

You're starting with some kind of assumed problem and explaining the solution, but I don't know what the problem is supposed to be.

Please explain in more detail.

**Comment by execut** [comment] 2017-03-24 10:49
This is more a question. I want to free myself from global locks in the work environment database when creating DDL queries. When applications fall due to global locking, this is very bad. I have a question about how to do this with BDR replication. What came to my mind is the 2 variant above

**Comment by ringerc** [comment] 2017-03-24 11:43
This is an issue/bug tracker, so please keep it for specific issues.

I'll close this ticket.

If you want to raise topics for general discussion please use the bdr and
pglogical mailing list at
https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list
​
I strongly advise you to read bdr-locks.c and understand *why* we do global
DDL locking before trying to solve issues around it. It's not as simple as
you think, it's a necessary consequence of an asynchronous system that can
perform arbitrary schema changes.

**Closed by ringerc** 2017-03-24 11:43 UTC
Labels: question

**Comment by execut** [comment] 2017-03-24 12:12
I know why need DDL locks, but only this is a very big problem in the working mode. When I do add a column of a large table, the programs will be stopped for hours. So I decided to find a way out of this situation.

**Comment by execut** [comment] 2017-03-24 12:16
It obviously needs a reserve database while the main one is locked. But how do it with BDR? BDR solution is blocked native PostgreSQL stream replication.

**Comment by ringerc** [comment] 2017-03-24 12:37
This ticket is closed. Please discuss this on the mailing list after reading the relevant source code.
